const fs = require('fs');
const path = 'D:/codex/novel-workshop-vue3/_audit/MEMORY_V1_CONSTRUCTION_PLAN.md';
const lines = [];
lines.push('# 记忆板块第一版「可靠基础闭环」施工计划');
lines.push('');
lines.push('**交付对象**：新对话框（无上下文，需完整自包含）');
lines.push('**施工目标**：D:\\codex\\novel-workshop-vue3');
lines.push('**范围**：第一版 A/B/C/D 四块，共 12 个任务');
lines.push('**铁律**：只改记忆板块相关文件，不碰流水线/去AI味/聊天/设置其他功能');
lines.push('');
lines.push('---');
lines.push('');
lines.push('## 零、施工前必读');
lines.push('');
lines.push('### 0.1 项目位置与启动方式');
lines.push('');
lines.push('- 源码根目录：D:\\codex\\novel-workshop-vue3');
lines.push('- 启动器：根目录下 start-electron.bat（先 npm run build:vue 再启动 Electron）');
lines.push('- 经验文件：_audit/神意开发经验总结.md（221KB，含全部教训）');
lines.push('- 规则文件：memory/rules.md（规则1-23）');
lines.push('- 错误日志：lessons/ERROR_LOG.md');
lines.push('- 审计报告：_audit/MEMORY_DEEP_AUDIT_AND_PLAN_REVIEW_2026-08-27.md');
lines.push('- 开发日志：_audit/DEV_LOG_2026-08-*.md（按日期命名）');
lines.push('');
lines.push('### 0.2 技术栈约束');
lines.push('');
lines.push('- Vue 3.5 + Pinia + Vite 5 + Electron 30 + TypeScript');
lines.push('- 禁止引入新 npm 依赖');
lines.push('- 禁止用 PowerShell Set-Content 修改含中文源文件（规则13）');
lines.push('- 含中文文件用 apply_patch 或 Node.js fs 写入');
lines.push('- 每次改完立即 node --check 验证语法');
lines.push('- CSS 先搜后改，禁止叠加（规则19）');
lines.push('');
lines.push('### 0.3 验证三铁律（规则14）');
lines.push('');
lines.push('1. 外部裁判：改完不能靠读代码判断通过。必须用 Playwright/CDP 实际操作应用，截图+JSON日志+时间戳三者缺一视为未验证');
lines.push('2. 行为验证：不验证「元素存在」，验证「功能能用」。必须验证 操作->预期行为->实际结果 三元组');
lines.push('3. 强制执行：每个阶段有验证清单，任何一项 FAIL 禁止进入下一阶段');
lines.push('');
lines.push('### 0.4 防空转协议');
lines.push('');
lines.push('- 每步写 _audit/checkpoint.md + update_plan');
lines.push('- 同一方法连续失败2次，强制换路径');
lines.push('- 子Agent必须真正spawn，不能只说「我去派」');
lines.push('- 每30秒给用户一条进度更新，连续两条说同样话=空转信号');
lines.push('- 工具调用前先确认工具在可用列表中，连续两次失败立刻换替代方案');
lines.push('');
lines.push('### 0.5 本计划引用的核心经验教训');
lines.push('');
lines.push('| 编号 | 教训摘要 | 来源 |');
lines.push('|------|---------|------|');
lines.push('| 教训#77 | Array分支读purpose必须覆盖verify/detect | 经验文件 ~L74 |');
lines.push('| 教训#78 | baseUrl含/vN后缀会导致路由失败 | 经验文件 ~L74 |');
lines.push('| 教训#80 | CDP脚本写成独立.cjs文件执行 | 经验文件 ~L488 |');
lines.push('| 教训#81 | 检查DOM不检查全局变量 | 经验文件 ~L488 |');
lines.push('| 记忆异步落盘 | recordMemoryChange后必须await saveProject | 经验文件 ~L1832 |');
lines.push('| normalizeMemories风险 | 只保留已知字段，新字段静默丢失 | project.ts:47-55 |');
lines.push('| Object.assign覆盖 | 合并器直接覆盖未比较字段 | memoryMerger.ts 事件/世界观/伏笔 |');
lines.push('| 导入覆盖风险 | 覆盖导入无备份不可撤销 | memoryIO.ts + MemoryPanel.vue:266 |');
lines.push('| 关闭只等500ms | lifecycle.js固定setTimeout 500ms不够 | lifecycle.js:11-29 |');
lines.push('| EditorPanel两套路径 | EditorPanel走getAiService，PipelinePanel走callMemoryApi | 经验文件 ~L514 |');
lines.push('| 空状态冒充 | 空状态不能冒充真实数据验证 | 经验文件 ~L1712 |');
lines.push('');
lines.push('---');
lines.push('');
lines.push('## A. 来源与版本基础（任务 A1-A3）');
lines.push('');
lines.push('### A1: 扩展记忆数据模型，增加来源与版本字段');
lines.push('');
lines.push('**目标**：每个记忆条目可追溯到正文版本、章节范围和来源片段。');
lines.push('');
lines.push('**改动文件**：');
lines.push('1. src/types/memory.ts（现有 139 行）');
lines.push('2. src/stores/project.ts 的 normalizeMemories() 函数（现有 L47-55）');
lines.push('');
lines.push('**具体改动**：');
lines.push('');
lines.push('在 src/types/memory.ts 中新增以下接口：');
lines.push('');
lines.push('```typescript');
lines.push('export interface SourceVersion {');
lines.push('  id: string');
lines.push('  chapterId: string');
lines.push('  chapterIndex: number');
lines.push('  contentHash: string');
lines.push('  savedAt: string');
lines.push('  wordCount: number');
lines.push('}');
lines.push('');
lines.push('export interface FactSource {');
lines.push('  sourceVersionId: string');
lines.push('  chapterId: string');
lines.push('  chapterIndex: number');
lines.push('  snippet: string');
lines.push('  rangeStart?: number');
lines.push('  rangeEnd?: number');
lines.push('  verified: boolean');
lines.push('}');
lines.push('');
lines.push('export type FactStatus = "confirmed" | "pending" | "stale" | "conflicted" | "rejected"');
lines.push('```');
lines.push('');
lines.push('在 MemoryEntity、MemoryRelation、MemoryEvent、WorldEntry、Foreshadowing 五个接口中各增加：');
lines.push('');
lines.push('```typescript');
lines.push('  factStatus?: FactStatus');
lines.push('  supersedesId?: string');
lines.push('  conflictsWithIds?: string[]');
lines.push('  factSource?: FactSource');
lines.push('```');
lines.push('');
lines.push('在 MemoryData 顶层增加：');
lines.push('');
lines.push('```typescript');
lines.push('  sourceVersions?: SourceVersion[]');
lines.push('```');
lines.push('');
lines.push('在 normalizeMemories()（project.ts L47-55）中增加对新字段的安全处理：');
lines.push('');
lines.push('```typescript');
lines.push('sourceVersions: Array.isArray(raw.sourceVersions) ? raw.sourceVersions : [],');
lines.push('// 五类数组中无 factStatus 的条目补 confirmed');
lines.push('for (const arr of [out.entities, out.relations, out.events, out.world, out.foreshadowing]) {');
lines.push('  for (const item of arr) {');
lines.push('    if (!item.factStatus) item.factStatus = "confirmed"');
lines.push('  }');
lines.push('}');
lines.push('```');
lines.push('');
lines.push('**输入输出契约**：');
lines.push('- 输入：旧 MemoryData（version=1，无 sourceVersions/factStatus）');
lines.push('- 输出：新 MemoryData（version=1，有 sourceVersions=[]，每条事实有 factStatus="confirmed"）');
lines.push('- 不破坏旧数据：旧项目加载后所有字段保留，新字段有默认值');
lines.push('');
lines.push('**错误路径**：');
lines.push('- raw 为 null/undefined -> 返回 createDefaultMemories()');
lines.push('- raw.sourceVersions 不是数组 -> 默认空数组');
lines.push('- 某条目无 factStatus -> 补 "confirmed"');
lines.push('');
lines.push('**验证方法**：');
lines.push('1. 写一个 Vitest 单元测试，加载一个旧格式 MemoryData JSON，断言新字段存在且有默认值');
lines.push('2. 用 CDP 启动应用，打开一个已有项目，检查记忆面板能正常加载旧数据');
lines.push('3. 关闭重启后检查 sourceVersions 和 factStatus 仍然存在');
lines.push('');
lines.push('**引用经验**：normalizeMemories 只保留已知字段，新字段会静默丢失（project.ts:47-55 实证）');
lines.push('');
lines.push('---');
lines.push('');
lines.push('### A2: 正文保存时记录版本');
lines.push('');
lines.push('**目标**：编辑器保存正文和流水线正文确认时，都产生同一格式的正文版本记录。');
lines.push('');
lines.push('**改动文件**：');
lines.push('1. src/stores/project.ts 新增 recordSourceVersion() 方法');
lines.push('2. src/components/pipeline/PipelinePanel.vue 的 confirmBodyWithMemory() 函数（现有 L2743）');
lines.push('3. src/components/editor/EditorPanel.vue 的保存路径');
lines.push('');
lines.push('**具体改动**：');
lines.push('');
lines.push('在 project.ts 新增方法：');
lines.push('');
lines.push('```typescript');
lines.push('function recordSourceVersion(chapterId, chapterIndex, content) {');
lines.push('  const hash = simpleHash(content)');
lines.push('  const existing = (memories.value.sourceVersions || []).find(v => v.chapterId === chapterId && v.contentHash === hash)');
lines.push('  if (existing) return existing.id');
lines.push('  const version = { id: "sv_"+Date.now()+"_"+Math.random().toString(36).slice(2,8), chapterId, chapterIndex, contentHash: hash, savedAt: new Date().toISOString(), wordCount: content.length }');
lines.push('  if (!memories.value.sourceVersions) memories.value.sourceVersions = []');
lines.push('  memories.value.sourceVersions.push(version)');
lines.push('  saveProject()');
lines.push('  return version.id');
lines.push('}');
lines.push('');
lines.push('function simpleHash(text) {');
lines.push('  let hash = 0');
lines.push('  for (let i = 0; i < text.length; i++) { hash = ((hash << 5) - hash + text.charCodeAt(i)) | 0 }');
lines.push('  return "h" + (hash >>> 0).toString(36)');
lines.push('}');
lines.push('```');
lines.push('');
lines.push('在 PipelinePanel.vue confirmBodyWithMemory() 中（L2743 附近），正文保存成功后调用：');
lines.push('');
lines.push('```typescript');
lines.push('const versionId = projectStore.recordSourceVersion(chapter.id, chapter.index, chapter.content)');
lines.push('```');
lines.push('');
lines.push('在 EditorPanel.vue 保存路径中同样调用 recordSourceVersion。');
lines.push('');
lines.push('**输入输出契约**：');
lines.push('- 输入：chapterId, chapterIndex, content');
lines.push('- 输出：sourceVersionId（写入 sourceVersions 数组并持久化）');
lines.push('- 同一内容不重复记录');
lines.push('');
lines.push('**错误路径**：');
lines.push('- content 为空 -> 不记录，返回空字符串');
lines.push('- saveProject 失败 -> versionId 仍返回，但不持久化（下次保存会重新记录）');
lines.push('');
lines.push('**验证方法**：');
lines.push('1. 单元测试：调用 recordSourceVersion 两次相同内容，断言只产生一条记录');
lines.push('2. CDP：流水线正文确认后，读取 projectStore.memories.sourceVersions，断言有一条记录');
lines.push('3. CDP：编辑器保存正文后，同样断言有记录');
lines.push('');
lines.push('**引用经验**：EditorPanel 与 PipelinePanel 存在两套 AI 调用路径（经验文件 ~L514），版本记录必须两边都接入');
lines.push('');
lines.push('---');
lines.push('');
lines.push('### A3: 抽取时为每条记忆绑定来源版本');
lines.push('');
lines.push('**目标**：AI 抽取返回的记忆条目，每条都带 factSource，包含 sourceVersionId。');
lines.push('');
lines.push('**改动文件**：');
lines.push('1. src/services/memoryExtractor.ts 的 ExtractionInput 接口（现有 L8-14）');
lines.push('2. src/composables/useMemoryExtraction.ts 的 start() 函数（现有 L62-87）');
lines.push('3. src/components/pipeline/PipelinePanel.vue 的抽取调用（L2763 附近）');
lines.push('');
lines.push('**具体改动**：');
lines.push('');
lines.push('在 ExtractionInput 中增加 sourceVersionId 字段。');
lines.push('');
lines.push('在 useMemoryExtraction.ts 的 start() 中，抽取成功后为每条结果补 factSource：');
lines.push('');
lines.push('```typescript');
lines.push('const sourceVersionId = input.sourceVersionId || ""');
lines.push('const injectSource = (items) => items.map((item) => ({');
lines.push('  ...item,');
lines.push('  factSource: item.factSource || {');
lines.push('    sourceVersionId,');
lines.push('    chapterId: input.chapterId,');
lines.push('    chapterIndex: input.chapterIndex || 0,');
lines.push('    snippet: item.evidence?.[0]?.snippet || "",');
lines.push('    verified: false');
lines.push('  },');
lines.push('  factStatus: item.factStatus || "pending"');
lines.push('}))');
lines.push('```');
lines.push('');
lines.push('在 PipelinePanel.vue 和 EditorPanel.vue 的抽取调用中传入 sourceVersionId。');
lines.push('');
lines.push('**验证方法**：');
lines.push('1. 单元测试：模拟抽取结果，断言每条都有 factSource 和 factStatus');
lines.push('2. CDP：流水线正文确认后抽取，读取预览中的变更项，检查 factSource 存在');
lines.push('3. 确认写入后，读取 projectStore.memories.entities，检查 factStatus 从 pending 变为 confirmed');
lines.push('');
lines.push('**引用经验**：evidence 必须对应真实正文（经验文件 ~L1830），snippet 在正文中真实存在校验在 B2 实现');
lines.push('');
lines.push('---');
lines.push('');
lines.push('## B. 抽取与证据（任务 B1-B3）');
lines.push('');
lines.push('### B1: 统一 EditorPanel 与 PipelinePanel 的抽取调用入口');
lines.push('');
lines.push('**目标**：两个面板调用记忆抽取时使用同一个服务入口，统一 purpose、超时、重试、取消和日志。');
lines.push('');
lines.push('**改动文件**：');
lines.push('1. src/services/memoryExtractor.ts（现有 155 行）');
lines.push('2. src/composables/useMemoryExtraction.ts（现有 132 行）');
lines.push('3. src/components/editor/EditorPanel.vue（现有抽取入口 ~L119-124）');
lines.push('4. src/components/pipeline/PipelinePanel.vue（现有抽取入口 ~L2763）');
lines.push('');
lines.push('**现状**（审计实证）：');
lines.push('- EditorPanel L119: const service = await getAiService() 然后 service.callAi({purpose: "generate", ...})');
lines.push('- PipelinePanel: 使用自身的 callMemoryApi/callApiWithAgent 路径');
lines.push('- 两套路径的 purpose、超时、重试策略不一致');
lines.push('');
lines.push('**具体改动**：');
lines.push('');
lines.push('在 memoryExtractor.ts 中新增统一调用封装 extractMemoryUnified()。');
lines.push('在 EditorPanel.vue 和 PipelinePanel.vue 中，都改为调用 extractMemoryUnified。');
lines.push('');
lines.push('**不改的部分**：');
lines.push('- PipelinePanel 的 callApiWithAgent 用于生成流水线的正文/大纲/卷纲等，不动');
lines.push('- EditorPanel 的其他 AI 调用（内联AI菜单等），不动');
lines.push('- 只统一记忆抽取这一个调用点');
lines.push('');
lines.push('**验证方法**：');
lines.push('1. 单元测试：mock getAiService，验证 extractMemoryUnified 调用 service.callAi 时的 purpose="generate"');
lines.push('2. CDP：EditorPanel 抽取和 PipelinePanel 抽取各跑一次，检查诊断日志中 purpose 字段一致');
lines.push('3. 对比两次调用的 timeoutMs 和 retry 字段是否一致');
lines.push('');
lines.push('**引用经验**：EditorPanel 与 PipelinePanel 存在两套 AI 调用路径（经验文件 ~L514），统一入口不等于改其他调用');
lines.push('');
lines.push('---');
lines.push('');
lines.push('### B2: snippet 在正文中的真实存在校验');
lines.push('');
lines.push('**目标**：AI 返回的 evidence snippet 必须在对应正文中真实出现，否则标记 verified=false 并进入待审核。');
lines.push('');
lines.push('**改动文件**：');
lines.push('1. src/services/memoryExtractor.ts 的 parseJson() 函数（现有 L35-51）');
lines.push('2. src/composables/useMemoryExtraction.ts 的 start() 函数');
lines.push('3. src/components/pipeline/PipelinePanel.vue 的抽取流程（L2773 附近）');
lines.push('');
lines.push('**现状**（审计实证）：');
lines.push('- memoryExtractor.ts L35-51 的 hasEvidence() 只检查 chapterId 和 snippet 非空');
lines.push('- 不验证 snippet 是否真实出现在正文中');
lines.push('- memoryMerger.ts L31 的 emptyEvidence() 甚至可以生成空 snippet');
lines.push('');
lines.push('**具体改动**：');
lines.push('');
lines.push('在 memoryExtractor.ts 中新增校验函数 verifySnippet(snippet, content)。');
lines.push('在 parseJson() 返回结果前，对每条 evidence 调用 verifySnippet。');
lines.push('parseJson 需要额外接收 originalContent 参数。');
lines.push('');
lines.push('**验证方法**：');
lines.push('1. 单元测试：构造包含和不包含 snippet 的正文，验证 verifySnippet 返回值');
lines.push('2. CDP：抽取后检查预览中有「未验证」标记的条目');
lines.push('3. 确认写入后，projectStore 中对应条目的 evidence 有 verified 字段');
lines.push('');
lines.push('**引用经验**：evidence 必须对应真实正文，空状态不能冒充真实数据验证（经验文件 ~L1712, ~L1830）');
lines.push('');
lines.push('---');
lines.push('');
lines.push('### B3: 抽取失败不阻塞正文保存 + 结构化日志');
lines.push('');
lines.push('**目标**：正文保存和记忆抽取解耦。抽取失败时正文已保存，用户可重试抽取。');
lines.push('');
lines.push('**改动文件**：');
lines.push('1. src/composables/useMemoryExtraction.ts 的 start() 函数');
lines.push('2. src/components/pipeline/PipelinePanel.vue 的 confirmBodyWithMemory() 函数（L2743-2783）');
lines.push('3. src/components/editor/EditorPanel.vue 的抽取流程');
lines.push('');
lines.push('**具体改动**：');
lines.push('');
lines.push('新增 ExtractionLog 接口，在 start() 各阶段记录结构化日志。');
lines.push('在 confirmBodyWithMemory() 中，确保正文保存发生在抽取之前：');
lines.push('1. 先保存正文');
lines.push('2. 记录版本');
lines.push('3. 再抽取（失败不回滚正文）');
lines.push('');
lines.push('**验证方法**：');
lines.push('1. CDP：模拟 AI 超时，检查正文已保存且 UI 显示重试');
lines.push('2. CDP：模拟 JSON 解析失败，检查正文已保存且 UI 显示重试');
lines.push('3. 读取诊断日志，检查结构化日志记录了 phase/error/duration');
lines.push('');
lines.push('**引用经验**：抽取失败不阻塞正文保存，断网/超时不丢正文（经验文件 ~L1839, ~L1851）');
lines.push('');
lines.push('---');
lines.push('');
lines.push('## C. 合并、审核与不覆盖（任务 C1-C3）');
lines.push('');
lines.push('### C1: 禁止 Object.assign 直接覆盖，改为字段级更新');
lines.push('');
lines.push('**目标**：合并器不能用 Object.assign 覆盖未比较的字段。');
lines.push('');
lines.push('**改动文件**：src/services/memoryMerger.ts（现有 235 行）');
lines.push('');
lines.push('**现状**（审计实证）：');
lines.push('- mergeEvents() L120: Object.assign(target, incoming, { updatedAt: now }) 直接覆盖');
lines.push('- mergeWorld() L137: Object.assign(target, incoming, { updatedAt: now }) 直接覆盖');
lines.push('- mergeForeshadowing() L155: Object.assign(target, incoming, { updatedAt: now }) 直接覆盖');
lines.push('');
lines.push('**具体改动**：');
lines.push('');
lines.push('对 mergeEvents()、mergeWorld()、mergeForeshadowing() 三个函数的更新分支，替换 Object.assign 为字段级更新。只更新有新值的字段，数组字段用追加。');
lines.push('');
lines.push('**不改的部分**：');
lines.push('- mergeEntity() 已经是字段级更新（不用 Object.assign），不动');
lines.push('- mergeRelations() 已经是字段级更新，不动');
lines.push('- 新增条目的分支不动');
lines.push('');
lines.push('**验证方法**：');
lines.push('1. 单元测试：已有事件 summary="旧", 抽取返回 summary="新", 断言旧被新替换');
lines.push('2. 单元测试：已有事件 characters=["A"], 抽取返回 characters=["B"], 断言结果为 ["A","B"]');
lines.push('3. 单元测试：锁定的事件不被更新');
lines.push('');
lines.push('**引用经验**：Object.assign 直接覆盖未比较字段是已审计的根因（memoryMerger.ts 实证）');
lines.push('');
lines.push('---');
lines.push('');
lines.push('### C2: 引入事实状态生命周期');
lines.push('');
lines.push('**目标**：新抽取的条目默认 pending，用户确认后变 confirmed；冲突条目标记 conflicted。');
lines.push('');
lines.push('**改动文件**：');
lines.push('1. src/services/memoryMerger.ts');
lines.push('2. src/composables/useMemoryExtraction.ts 的 confirm() 函数（现有 L99-119）');
lines.push('3. src/components/pipeline/PipelinePanel.vue 的 confirmMemoryPreview() 函数（L2796-2824）');
lines.push('');
lines.push('**具体改动**：');
lines.push('');
lines.push('在 memoryMerger.ts 合并逻辑中，处理 factStatus：');
lines.push('- target.factStatus="confirmed" 且 incoming.factStatus="pending" -> 标记 conflicted');
lines.push('- 用户确认后 factStatus 从 pending 改为 confirmed');
lines.push('');
lines.push('在 confirm() 中，确认写入时把 factStatus 从 pending 改为 confirmed。');
lines.push('在 PipelinePanel.vue 的 confirmMemoryPreview() 中做同样处理。');
lines.push('');
lines.push('**验证方法**：');
lines.push('1. 单元测试：confirmed + pending 同一实体 -> 断言 conflicted');
lines.push('2. CDP：抽取后确认写入，读取 projectStore，检查 factStatus=confirmed');
lines.push('3. CDP：拒绝一条，检查对应条目不在 memories 中或标记为 rejected');
lines.push('');
lines.push('**引用经验**：引入 confirmed/pending/stale/conflicted/rejected 状态（审计报告第4节C项）');
lines.push('');
lines.push('---');
lines.push('');
lines.push('### C3: 导入默认合并，覆盖需二次确认+备份');
lines.push('');
lines.push('**目标**：导入记忆 JSON 时默认合并，覆盖导入必须先备份再覆盖，且支持撤销。');
lines.push('');
lines.push('**改动文件**：');
lines.push('1. src/components/common/MemoryPanel.vue 的 importMemory() 函数（现有 L266-282 附近）');
lines.push('2. src/services/memoryIO.ts（现有 183 行）');
lines.push('');
lines.push('**现状**（审计实证）：');
lines.push('- MemoryPanel.vue L266-282: 导入成功后直接 projectStore.memories = result.memory');
lines.push('- 覆盖导入提示「将覆盖当前记忆数据」，但无备份、无撤销');
lines.push('- memoryIO.ts 有 mergeImportedMemory() 函数（正确），但覆盖路径不用它');
lines.push('');
lines.push('**具体改动**：');
lines.push('');
lines.push('覆盖导入路径增加：二次确认 + 备份到 localStorage + 覆盖 + 撤销提示。');
lines.push('合并导入路径改用 mergeImportedMemory() + recordMemoryChange()。');
lines.push('在 memoryIO.ts 中增加 recoverFromBackup() 函数。');
lines.push('');
lines.push('**验证方法**：');
lines.push('1. 单元测试：覆盖导入后检查备份存在，且可恢复');
lines.push('2. CDP：覆盖导入后检查项目存储中有备份 key');
lines.push('3. CDP：合并导入后检查原有数据不丢失');
lines.push('4. CDP：坏 JSON 导入后检查当前数据不变');
lines.push('');
lines.push('**引用经验**：导入合并与覆盖必须分开，覆盖导入无备份不可撤销（经验文件 ~L1785, ~L1800）');
lines.push('');
lines.push('---');
lines.push('');
lines.push('## D. 持久化、并发和 UI（任务 D1-D3）');
lines.push('');
lines.push('### D1: saveProject 写入队列 + 关闭流程等待');
lines.push('');
lines.push('**目标**：所有 saveProject 调用排队执行，关闭应用时等待最终保存完成。');
lines.push('');
lines.push('**改动文件**：');
lines.push('1. src/stores/project.ts 的 saveProject() 函数（现有 L166-183）');
lines.push('2. electron/ipc/lifecycle.js（现有 29 行）');
lines.push('3. src/App.vue 或主进程的关闭处理逻辑');
lines.push('');
lines.push('**现状**（审计实证）：');
lines.push('- project.ts 的 saveProject() 是 async，但大量调用点没有 await（经验文件 ~L1832）');
lines.push('- lifecycle.js L21: setTimeout(function() { mainWindow.close() }, 500) 固定等500ms');
lines.push('- 500ms 可能不够等待 saveProject 完成');
lines.push('');
lines.push('**具体改动**：');
lines.push('');
lines.push('在 project.ts 中增加写入队列：连续多次 saveProject 只执行最后一次。');
lines.push('在 lifecycle.js 中，把固定 500ms 改为等待 finalSave 完成的 Promise（最多5秒超时保底）。');
lines.push('在 App.vue 中，监听 app:finalSave 后调用 projectStore.saveProject()，完成后 ipcRenderer.send("app:saveComplete")。');
lines.push('');
lines.push('**验证方法**：');
lines.push('1. 单元测试：连续调用 saveProject 3次，断言只执行1次 storageWrite');
lines.push('2. CDP：打开项目，修改数据，关闭应用，重启后检查数据一致');
lines.push('3. CDP：杀进程后重启，检查数据未丢失');
lines.push('');
lines.push('**引用经验**：关闭只等500ms不够（lifecycle.js:11-29 实证），recordMemoryChange后必须await saveProject（经验文件 ~L1832）');
lines.push('');
lines.push('---');
lines.push('');
lines.push('### D2: 项目切换时取消/隔离旧请求');
lines.push('');
lines.push('**目标**：切换项目时，旧项目的 AI 请求不回写到新项目 Store。');
lines.push('');
lines.push('**改动文件**：');
lines.push('1. src/stores/project.ts 的 loadProject() 和 clearCurrent() 函数');
lines.push('2. src/composables/useMemoryExtraction.ts');
lines.push('3. src/components/pipeline/PipelinePanel.vue 的抽取流程');
lines.push('');
lines.push('**具体改动**：');
lines.push('');
lines.push('在 loadProject() 开头记录 projectIdAtCall，异步加载后检查是否仍为当前项目。');
lines.push('在 useMemoryExtraction.ts 的 start() 和 confirm() 中增加项目 ID 检查。');
lines.push('在 PipelinePanel.vue 的抽取流程中做同样检查。');
lines.push('');
lines.push('**验证方法**：');
lines.push('1. CDP：在项目A中开始抽取，中途切换到项目B，等待抽取完成，检查项目B的记忆没有被写入');
lines.push('2. CDP：在项目A中抽取完成后但未确认写入时切换到项目B，检查项目B不受影响');
lines.push('');
lines.push('**引用经验**：异步保存竞态、切换期间请求回写、跨项目缓存污染（审计报告第2节#26）');
lines.push('');
lines.push('---');
lines.push('');
lines.push('### D3: MemoryPanel 新模型统一 CRUD + 五视图验证');
lines.push('');
lines.push('**目标**：MemoryPanel 不再「新模型只读+旧模型可编辑」，五类记忆都支持统一 CRUD。');
lines.push('');
lines.push('**改动文件**：');
lines.push('1. src/components/common/MemoryPanel.vue（现有约300行）');
lines.push('2. 可能涉及 src/components/memory/RelationGraph.vue、TimelineView.vue 等子组件');
lines.push('');
lines.push('**现状**（审计实证）：');
lines.push('- MemoryPanel.vue L132-245: 旧 items 有编辑/删除按钮，新模型没有');
lines.push('- legacyIndex 用于旧 items 的索引，新模型用 entity.id 等');
lines.push('- 展示索引与 legacyIndex 可能错位');
lines.push('');
lines.push('**具体改动**：');
lines.push('');
lines.push('为新模型五类增加 CRUD 按钮，调用 projectStore 的 updateEntity、deleteEntity、lockEntityField 等已有方法。');
lines.push('对关系、事件、世界观、伏笔也增加编辑/删除/锁定按钮。');
lines.push('移除 legacyIndex 的混用。');
lines.push('');
lines.push('**验证方法**：');
lines.push('1. CDP：打开记忆面板，编辑一个实体，检查五视图都更新');
lines.push('2. CDP：删除一个实体，检查关联关系也被清理');
lines.push('3. CDP：锁定一个实体字段，重新抽取后检查该字段不被覆盖');
lines.push('4. CDP：用真实非空数据（不是空状态）验证五视图');
lines.push('');
lines.push('**引用经验**：MemoryPanel 展示索引与 legacyIndex 可能错位（审计报告第2节#22），空状态不能冒充真实数据验证（经验文件 ~L1712）');
lines.push('');
lines.push('---');
lines.push('');
lines.push('## 任务依赖与执行顺序');
lines.push('');
lines.push('```text');
lines.push('A1 -> A2 -> A3 -> B1 + B2 -> B3 -> C1 -> C2 -> C3 -> D1 -> D2 -> D3');
lines.push('```');
lines.push('');
lines.push('A1 必须先做，因为后续所有任务都依赖新字段。D3 最后做，因为它依赖所有数据模型和存储改动完成。B1 和 B2 可以并行，但建议顺序执行避免冲突。C1-C3 有依赖关系，不能并行。D1-D3 有依赖关系，不能并行。');
lines.push('');
lines.push('---');
lines.push('');
lines.push('## 第一版硬验收门');
lines.push('');
lines.push('以下全部通过才算第一版完成。任何一项未通过，不算完成。');
lines.push('');
lines.push('| 编号 | 验收项 | 验证方法 | 通过标准 |');
lines.push('|------|--------|---------|--------|');
lines.push('| V1 | 新旧项目加载后字段一致 | Vitest + CDP | 旧项目加载后 sourceVersions=[], factStatus="confirmed" |');
lines.push('| V2 | 正文确认后版本记录存在 | CDP | projectStore.memories.sourceVersions 有记录 |');
lines.push('| V3 | 抽取结果每条有 factSource | Vitest | 断言 factSource.sourceVersionId 非空 |');
lines.push('| V4 | EditorPanel和PipelinePanel统一入口 | CDP | 诊断日志中 purpose/timeoutMs 一致 |');
lines.push('| V5 | snippet 校验功能 | Vitest | verified=true/false 正确 |');
lines.push('| V6 | 抽取失败正文已保存 | CDP | 超时后正文在 projectStore 中 |');
lines.push('| V7 | Object.assign 已替换 | 代码审查 | mergeEvents/World/Foreshadowing 无 Object.assign |');
lines.push('| V8 | 事实状态生命周期 | Vitest + CDP | pending->confirmed, 冲突标记 conflicted |');
lines.push('| V9 | 导入合并不覆盖 | CDP | 合并后原有数据保留 |');
lines.push('| V10 | 覆盖导入有备份 | CDP | 备份 key 存在 |');
lines.push('| V11 | 坏JSON不改变数据 | CDP | 当前数据不变 |');
lines.push('| V12 | saveProject 队列执行 | Vitest | 连续3次只写1次 |');
lines.push('| V13 | 关闭重开数据一致 | CDP | 杀进程重启后记忆数据一致 |');
lines.push('| V14 | 项目切换不串写 | CDP | 切换后旧请求不写入新项目 |');
lines.push('| V15 | MemoryPanel CRUD | CDP | 五类记忆可编辑/删除/锁定，五视图更新 |');
lines.push('| V16 | 五视图真实非空数据 | CDP | 关系图/时间线/图谱/思维导图/画像卡有内容 |');
lines.push('');
lines.push('---');
lines.push('');
lines.push('## 验证矩阵（每项验证必须产出）');
lines.push('');
lines.push('| 验证层 | 必须证明 | 证据形式 |');
lines.push('|--------|---------|---------|');
lines.push('| 静态链路 | UI事件->服务->Store->持久化 | 文件/函数/调用关系/字段读写 |');
lines.push('| 单元契约 | 解析/校验/合并/迁移边界正确 | Vitest 原始输出 |');
lines.push('| 组合链路 | 正文保存->抽取->审核->写入->视图更新 | CDP操作日志+状态前后对照 |');
lines.push('| 错误路径 | 超时/断网/非法JSON/取消/重复不丢正文 | 错误日志+恢复后状态 |');
lines.push('| 持久化 | 关闭重开后数据一致 | 文件快照before/after+重启后读取 |');
lines.push('| 隔离 | 切换项目不串写 | 两个项目的独立ID/请求/文件对照 |');
lines.push('| 视觉交互 | 五视图真实数据+筛选+来源跳转 | 截图+DOM状态+应用日志 |');
lines.push('');
lines.push('---');
lines.push('');
lines.push('## 禁止事项');
lines.push('');
lines.push('1. 禁止把代码存在当作真实行为通过');
lines.push('2. 禁止用空状态冒充真实数据验证');
lines.push('3. 禁止用构建成功覆盖类型检查/测试/CDP/安装包验收');
lines.push('4. 禁止用受控API响应冒充供应商稳定性');
lines.push('5. 禁止跳过验证步骤进入下一步');
lines.push('6. 禁止引入新 npm 依赖');
lines.push('7. 禁止用 PowerShell Set-Content 写含中文源文件');
lines.push('8. 禁止批量正则替换，必须精准修复');
lines.push('9. 禁止 Object.assign 直接覆盖未比较字段');
lines.push('10. 禁止覆盖导入无备份');
lines.push('');
lines.push('---');
lines.push('');
lines.push('## 施工流程模板（每个任务必须遵循）');
lines.push('');
lines.push('```text');
lines.push('1. 读经验文件相关教训');
lines.push('2. 读当前源码（具体文件/函数/行号）');
lines.push('3. 用 apply_patch 或 Node.js fs 修改');
lines.push('4. node --check 验证语法');
lines.push('5. npm run build:vue 验证构建');
lines.push('6. 写 Vitest 单元测试（如适用）');
lines.push('7. start-electron.bat 启动应用');
lines.push('8. CDP/Playwright 行为验证');
lines.push('9. 截图 + JSON日志 + 时间戳');
lines.push('10. 更新 _audit/checkpoint.md');
lines.push('11. 更新 update_plan');
lines.push('12. 验证通过后才进入下一任务');
lines.push('```');
lines.push('');
lines.push('---');
lines.push('');
lines.push('## 当前已知文件清单（施工前必读）');
lines.push('');
lines.push('| 文件 | 行数 | 职责 |');
lines.push('|------|------|------|');
lines.push('| src/types/memory.ts | ~139 | 记忆数据模型定义 |');
lines.push('| src/services/memoryExtractor.ts | ~155 | AI单阶段抽取 |');
lines.push('| src/services/memoryMerger.ts | ~235 | 增量合并（有Object.assign覆盖风险） |');
lines.push('| src/services/memoryVersion.ts | ~95 | 快照式 before/after 版本 |');
lines.push('| src/services/memoryIO.ts | ~183 | 导入导出+合并+覆盖 |');
lines.push('| src/services/memoryRetriever.ts | ~100 | 字符串匹配检索 |');
lines.push('| src/services/memoryExport.ts | ~140 | 角色画像/故事线/时间线/场景导出 |');
lines.push('| src/stores/project.ts | ~730 | 项目Store（memories响应式状态+normalizeMemories） |');
lines.push('| src/composables/useMemoryExtraction.ts | ~132 | 抽取+预览+审核+确认组合式 |');
lines.push('| src/components/common/MemoryPanel.vue | ~300 | 记忆面板UI（新旧混排） |');
lines.push('| src/components/pipeline/PipelinePanel.vue | ~2900 | 流水线（含正文确认+抽取入口） |');
lines.push('| src/components/editor/EditorPanel.vue | ~130 | 编辑器（含记忆抽取入口） |');
lines.push('| src/components/chat/ChatPanel.vue | ~500 | 聊天（retrieveContext注入） |');
lines.push('| electron/ipc/lifecycle.js | ~29 | Electron关闭流程（固定500ms） |');
lines.push('| src/services/aiService.ts | ~340 | 统一AI服务（purpose路由） |');
lines.push('');
lines.push('---');
lines.push('');
lines.push('## 附录：审计报告关键发现摘要');
lines.push('');
lines.push('以下来自 _audit/MEMORY_DEEP_AUDIT_AND_PLAN_REVIEW_2026-08-27.md 的 26 维审计矩阵：');
lines.push('');
lines.push('**当前状态**：');
lines.push('- 基础记忆模型：PARTIAL');
lines.push('- 正文抽取审核写入：PARTIAL');
lines.push('- 记忆面板与五视图：PARTIAL');
lines.push('- 生成流水线/聊天读取：PARTIAL');
lines.push('- 保存恢复与多项目隔离：PARTIAL');
lines.push('- 记忆线对齐与修改影响传播：MISSING');
lines.push('- 动画/短剧真实板块：MISSING');
lines.push('- 全量真实行为验收：UNVERIFIED');
lines.push('');
lines.push('**第一版只解决 PARTIAL -> PASS 的升级，不解决 MISSING（那是第二版/第三版的范围）。**');
lines.push('');
lines.push('**根因总结**：');
lines.push('1. 把记忆对象当成记忆事实（缺来源、版本、状态）');
lines.push('2. 抽取/合并/检索之间缺少同一条来源主键');
lines.push('3. EditorPanel 与 PipelinePanel 存在两套调用路径');
lines.push('4. UI 是「新模型只读+旧模型可编辑」的过渡态');
lines.push('5. 历史验收把静态证据和行为证据混在一起');
lines.push('');
lines.push('**第一版的目标就是把根因 1-5 全部从 PARTIAL 升级到 PASS。**');
lines.push('');
fs.writeFileSync(path, lines.join('\n'), 'utf8');
console.log('OK ' + lines.length + ' lines');
