$content = Get-Content "src/components/pipeline/PipelinePanel.vue" -Raw
$target = "async function runStepSkills(step: number, prompt: string, timeoutMs?: number, fallbackTemplate?: string): Promise<string> {`r`n  const templates = getStepSkillTemplates(step)`r`n  const mode = getStepSkillMode(step)`r`n  if (mode === `"chain`" && templates.length > 1) {"
$replacement = "async function runStepSkills(step: number, prompt: string, timeoutMs?: number, fallbackTemplate?: string): Promise<string> {`r`n  const templates = getStepSkillTemplates(step)`r`n  const mode = getStepSkillMode(step)`r`n  // Use SkillExecutionEngine for split-merge / multi-step`r`n  if ((mode === `"split-merge`" || mode === `"multi-step`") && templates.length > 0) {`r`n    const engine = (window as any).SkillExecutionEngine`r`n    if (engine) {`r`n      const aiRequest = async (opts: any) => {`r`n        const provider = providerStore.getProvider(`"`")`r`n        const preferredProvider = providerStore.preferredGenerateProvider`r`n        const activeProvider = provider || preferredProvider`r`n        const model = activeProvider?.selectedModel || activeProvider?.models?.[0] || `"`"`r`n        const sysMsg = opts.messages?.find((m: any) => m.role === `"system`")?.content || `"`"`r`n        const userMsg = opts.messages?.find((m: any) => m.role === `"user`")?.content || `"`"`r`n        const result = await providerStore.callApi(activeProvider?.id || `"`", model, [{ role: `"system`", content: sysMsg }, { role: `"user`", content: userMsg }])`r`n        return { text: result }`r`n      }`r`n      const engineSkills = templates.map((t: any) => ({ name: t.name, template: t.template }))`r`n      let result: any`r`n      if (mode === `"split-merge`") {`r`n        console.log(`"[PIPELINE] split-merge mode, step=`" + step + `" skills=`" + engineSkills.length)`r`n        result = await engine.splitMerge(prompt, engineSkills, { aiRequest, splitSize: 1000, stream: false })`r`n      } else {`r`n        console.log(`"[PIPELINE] multi-step mode, step=`" + step + `" skills=`" + engineSkills.length)`r`n        result = await engine.multiStep(prompt, engineSkills.slice(0, 4), { aiRequest, splitSize: 1500, stream: false })`r`n      }`r`n      return result?.text || prompt`r`n    }`r`n  }`r`n  if (mode === `"chain`" && templates.length > 1) {"
if ($content.Contains($target)) {
  $content = $content.Replace($target, $replacement)
  Set-Content "src/components/pipeline/PipelinePanel.vue" $content -NoNewline
  Write-Output "OK"
} else {
  Write-Output "TARGET NOT FOUND"
}
