const fs = require('fs');
const p = 'D:/codex/novel-workshop-vue3/src/components/common/PluginMarket.vue';
const L = [];
L.push('<template>');
L.push('  <div class="plugin-market-modal" @click.self="$emit(\'close\')">');
L.push('    <div class="modal-backdrop"></div>');
L.push('    <div class="modal-content market-modal-content">');
L.push('      <div class="modal-header">');
L.push('        <h3>\u63d2\u4ef6\u5e02\u573a</h3>');
L.push('        <button class="btn-close" @click="$emit(\'close\')">&times;</button>');
L.push('      </div>');
L.push('      <div class="modal-body market-body-scroll">');
L.push('        <div class="github-status-bar">');
L.push('          <span class="github-status-text">{{ tokenStatus }}</span>');
L.push('          <span>');
L.push('            <button class="btn-sm btn-mr-4" @click="showTokenInput = !showTokenInput">\u8bbe\u7f6e Token</button>');
L.push('            <button class="btn-sm btn-outline" @click="showTokenHelp = !showTokenHelp">\u5982\u4f55\u83b7\u53d6?</button>');
L.push('          </span>');
L.push('        </div>');
L.push('        <div v-if="showTokenInput" class="token-input-area">');
L.push('          <div class="token-help-text">\u8bf7\u8f93\u5165 GitHub Personal Access Token\uff08\u9700\u8981 public_repo \u6743\u9650\uff09</div>');
L.push('          <div class="token-input-row">');
L.push('            <input type="password" v-model="githubToken" placeholder="ghp_xxxxxxxxxxxx" class="token-input-field">');
L.push('            <button class="btn-primary btn-sm" @click="saveToken">\u4fdd\u5b58\u5e76\u9a8c\u8bc1</button>');
L.push('          </div>');
L.push('        </div>');
L.push('        <div v-if="showTokenHelp" class="token-help-area">');
L.push('          <strong>\u5982\u4f55\u83b7\u53d6 GitHub Token\uff1f</strong><br>');
L.push('          1. \u6253\u5f00 github.com/settings/tokens<br>');
L.push('          2. \u70b9\u51fb Generate new token (classic)<br>');
L.push('          3. \u52fe\u9009 public_repo \u6743\u9650<br>');
L.push('          4. \u70b9\u51fb\u751f\u6210\uff0c\u590d\u5236 ghp_ \u5f00\u5934\u7684\u5b57\u7b26\u4e32<br>');
L.push('          5. \u7c98\u8d34\u5230\u4e0a\u65b9\u8f93\u5165\u6846');
L.push('        </div>');
L.push('        <div class="market-search">');
L.push('          <input type="text" v-model="searchQuery" placeholder="\u641c\u7d22 GitHub \u4ed3\u5e93" class="market-search-input" @keydown.enter="searchGitHub">');
L.push('          <select v-model="searchCategory" class="market-category-select">');
L.push('            <option value="">\u5168\u90e8</option>');
L.push('            <option value="agent">Agent</option>');
L.push('            <option value="skill">Skill</option>');
L.push('          </select>');
L.push('          <button class="btn-primary" @click="searchGitHub">\u641c\u7d22</button>');
L.push('          <select v-model="searchSort" class="market-sort-select">');
L.push('            <option value="stars">\u6309\u661f\u6807</option>');
L.push('            <option value="updated">\u6309\u66f4\u65b0</option>');
L.push('            <option value="">\u6700\u4f73\u5339\u914d</option>');
L.push('          </select>');
L.push('        </div>');
L.push('        <div class="market-status-text">{{ marketStatus }}</div>');
L.push('        <div class="market-results-container market-results-scroll">');
L.push('          <div v-if="marketResults.length === 0 && !searching" class="empty-hint">\u8f93\u5165\u5173\u952e\u8bcd\u641c\u7d22 GitHub \u4e0a\u7684 Agent \u548c Skill</div>');
L.push('          <div v-for="item in marketResults" :key="item.id" class="market-item">');
L.push('            <div class="market-item-header">');
L.push('              <a :href="item.html_url" target="_blank" class="market-item-name">{{ item.full_name }}</a>');
L.push('              <span class="market-item-stars">\u2605 {{ item.stargazers_count }}</span>');
L.push('            </div>');
L.push('            <p class="market-item-desc">{{ item.description }}</p>');
L.push('            <button class="btn-sm btn-primary" @click="installFromMarket(item)">\u5b89\u88c5</button>');
L.push('          </div>');
L.push('        </div>');
L.push('        <div class="market-pagination">');
L.push('          <button class="btn-sm" :disabled="currentPage <= 1" @click="goToPage(currentPage - 1)">\u4e0a\u4e00\u9875</button>');
L.push('          <span class="page-info-text">\u7b2c {{ currentPage }} \u9875</span>');
L.push('          <button class="btn-sm" :disabled="marketResults.length < perPage" @click="goToPage(currentPage + 1)">\u4e0b\u4e00\u9875</button>');
L.push('        </div>');
L.push('      </div>');
L.push('    </div>');
L.push('  </div>');
L.push('</template>');
L.push('');
L.push('<script setup lang="ts">');
L.push('import { ref, onMounted } from \'vue\'');
L.push('');
L.push('defineEmits<{ close: [] }>()');
L.push('');
L.push('const showTokenInput = ref(false)');
L.push('const showTokenHelp = ref(false)');
L.push('const githubToken = ref(\'\'')');
L.push('const tokenStatus = ref(\'GitHub: \u672a\u767b\u5f55\'')');
L.push('const searchQuery = ref(\'\'')');
L.push('const searchCategory = ref(\'\'')');
L.push('const searchSort = ref(\'stars\'')');
L.push('const marketStatus = ref(\'\u8f93\u5165\u5173\u952e\u8bcd\u641c\u7d22 GitHub \u4e0a\u7684 Agent \u548c Skill\'')');
L.push('const marketResults = ref<any[]>([])');
L.push('const searching = ref(false)');
L.push('const currentPage = ref(1)');
L.push('const perPage = ref(10)');
L.push('');
L.push('onMounted(() => {');
L.push('  const saved = localStorage.getItem(\'wa_github_token\'')');
L.push('  if (saved) {');
L.push('    githubToken.value = saved');
L.push('    tokenStatus.value = \'GitHub: \u5df2\u8bbe\u7f6e Token\'');
L.push('  }');
L.push('})');
L.push('');
L.push('function saveToken() {');
L.push('  if (!githubToken.value) {');
L.push('    tokenStatus.value = \'GitHub: Token \u4e0d\u80fd\u4e3a\u7a7a\'');
L.push('    return');
L.push('  }');
L.push('  localStorage.setItem(\'wa_github_token\', githubToken.value)');
L.push('  tokenStatus.value = \'GitHub: \u5df2\u8bbe\u7f6e Token\'');
L.push('  showTokenInput.value = false');
L.push('}');
L.push('');
L.push('async function searchGitHub() {');
L.push('  if (!searchQuery.value.trim()) {');
L.push('    marketStatus.value = \'\u8bf7\u8f93\u5165\u641c\u7d22\u5173\u952e\u8bcd\'');
L.push('    return');
L.push('  }');
L.push('  searching.value = true');
L.push('  marketStatus.value = \'\u641c\u7d22\u4e2d...\'');
L.push('  try {');
L.push('    const q = searchQuery.value.trim()');
L.push('    const sort = searchSort.value || \'best-match\'');
L.push('    const token = localStorage.getItem(\'wa_github_token\'')');
L.push('    const headers: Record<string, string> = { \'Accept\': \'application/vnd.github.v3+json\' }');
L.push('    if (token) headers[\'Authorization\'] = \'token \' + token');
L.push('    const url = \'https://api.github.com/search/repositories?q=\' + encodeURIComponent(q) + \'&sort=\' + sort + \'&per_page=\' + perPage.value + \'&page=\' + currentPage.value');
L.push('    const resp = await fetch(url, { headers })');
L.push('    if (resp.status === 403) {');
L.push('      marketStatus.value = \'API \u9650\u6d41\uff0c\u8bf7\u8bbe\u7f6e GitHub Token\'');
L.push('      return');
L.push('    }');
L.push('    if (!resp.ok) throw new Error(\'GitHub API error: \' + resp.status)');
L.push('    const data = await resp.json()');
L.push('    marketResults.value = data.items || []');
L.push('    marketStatus.value = \'\u627e\u5230 \' + (data.total_count || 0) + \' \u4e2a\u4ed3\u5e93\'');
L.push('  } catch (e: any) {');
L.push('    marketStatus.value = \'\u641c\u7d22\u5931\u8d25: \' + (e.message || String(e))');
L.push('  } finally {');
L.push('    searching.value = false');
L.push('  }');
L.push('}');
L.push('');
L.push('function goToPage(page: number) {');
L.push('  currentPage.value = page');
L.push('  searchGitHub()');
L.push('}');
L.push('');
L.push('function installFromMarket(item: any) {');
L.push('  const name = item.name || \'unknown\'');
L.push('  const url = item.html_url || \'\'');
L.push('  window.dispatchEvent(new CustomEvent(\'plugin-install\', { detail: { name, url, type: searchCategory.value || \'agent\' } }))');
L.push('  marketStatus.value = \'\u6b63\u5728\u5b89\u88c5: \' + name');
L.push('}');
L.push('</script>');
L.push('');
L.push('<style scoped>');
L.push('.plugin-market-modal { position: fixed; top: 0; left: 0; right: 0; bottom: 0; z-index: 1000; display: flex; align-items: center; justify-content: center; }');
L.push('.modal-backdrop { position: absolute; top: 0; left: 0; right: 0; bottom: 0; background: var(--bg-overlay); }');
L.push('.market-modal-content { position: relative; width: min(800px, 92vw); max-height: 88vh; background: var(--bg-glass); border: 1px solid var(--border-color); border-radius: 12px; box-shadow: var(--shadow-lg); display: flex; flex-direction: column; }');
L.push('.modal-header { display: flex; align-items: center; justify-content: space-between; padding: 16px 24px; border-bottom: 1px solid var(--border-color); }');
L.push('.modal-header h3 { margin: 0; font-size: 16px; font-weight: 600; }');
L.push('.btn-close { background: none; border: none; font-size: 20px; cursor: pointer; color: var(--text-secondary); }');
L.push('.market-body-scroll { flex: 1; overflow-y: auto; padding: 16px 24px; }');
L.push('.github-status-bar { display: flex; align-items: center; justify-content: space-between; padding: 8px 12px; background: var(--bg-input); border-radius: 6px; margin-bottom: 12px; }');
L.push('.github-status-text { font-size: 13px; color: var(--text-secondary); }');
L.push('.btn-sm { font-size: 12px; padding: 4px 10px; border: 1px solid var(--border-color); border-radius: 4px; cursor: pointer; background: var(--bg-secondary); color: var(--text-primary); }');
L.push('.btn-mr-4 { margin-right: 4px; }');
L.push('.btn-outline { background: transparent; }');
L.push('.token-input-area { padding: 12px; background: var(--bg-input); border-radius: 6px; margin-bottom: 12px; }');
L.push('.token-help-text { font-size: 12px; color: var(--text-secondary); margin-bottom: 8px; }');
L.push('.token-input-row { display: flex; gap: 8px; }');
L.push('.token-input-field { flex: 1; background: var(--bg-primary); color: var(--text-primary); border: 1px solid var(--border-color); border-radius: 4px; padding: 4px 10px; font-size: 13px; height: 30px; }');
L.push('.btn-primary { background: var(--accent); color: var(--text-on-accent); border: none; border-radius: 4px; padding: 4px 12px; cursor: pointer; font-size: 12px; height: 30px; }');
L.push('.token-help-area { padding: 12px; background: var(--bg-input); border-radius: 6px; margin-bottom: 12px; font-size: 12px; line-height: 1.8; color: var(--text-secondary); }');
L.push('.market-search { display: flex; gap: 8px; margin-bottom: 12px; }');
L.push('.market-search-input { flex: 1; background: var(--bg-input); color: var(--text-primary); border: 1px solid var(--border-color); border-radius: 4px; padding: 4px 10px; font-size: 13px; height: 30px; }');
L.push('.market-category-select, .market-sort-select { background: var(--bg-input); color: var(--text-primary); border: 1px solid var(--border-color); border-radius: 4px; padding: 0 8px; font-size: 12px; height: 30px; }');
L.push('.market-status-text { font-size: 12px; color: var(--text-secondary); margin-bottom: 8px; }');
L.push('.market-results-container { min-height: 200px; }');
L.push('.market-results-scroll { max-height: 400px; overflow-y: auto; }');
L.push('.market-item { padding: 12px; border: 1px solid var(--border-color); border-radius: 6px; margin-bottom: 8px; }');
L.push('.market-item-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 4px; }');
L.push('.market-item-name { font-size: 13px; font-weight: 600; color: var(--accent); text-decoration: none; }');
L.push('.market-item-stars { font-size: 12px; color: var(--text-muted); }');
L.push('.market-item-desc { font-size: 12px; color: var(--text-secondary); margin: 0 0 8px 0; line-height: 1.5; }');
L.push('.empty-hint { text-align: center; color: var(--text-muted); padding: 40px 0; font-size: 13px; }');
L.push('.market-pagination { display: flex; align-items: center; gap: 12px; justify-content: center; padding: 12px 0; }');
L.push('.page-info-text { font-size: 12px; color: var(--text-secondary); }');
L.push('</style>');
L.push('');
const content = L.join('\n');
fs.writeFileSync(p, content, 'utf8');
const stat = fs.statSync(p);
console.log('[OK] PluginMarket.vue written, size:', stat.size);
