const fs = require('fs');
const dir = 'D:/codex/novel-workshop-vue3/_audit/manual/';
const files = {};
files['T02_调用链层.md'] = [
'# T02 - 调用链层',
'',
'## 核心调用入口',
'',
'### 1. _aiRequest(cfg) - 统一AI请求公共方法',
'- 位置: renderer_v2.js L2317',
'- 职责: 所有AI API调用的统一入口，支持流式/非流式、重试、空闲检测',
'- 参数: { baseUrl, apiKey, messages, model, temperature, maxTokens, stream, signal, onPause, onChunk }',
'- 行为契约:',
'  1. 构建请求URL: baseUrl + /chat/completions',
'  2. headers: Authorization Bearer + apiKey',
'  3. POST请求，body为标准OpenAI格式',
'  4. 流式: ReadableStream读取，chunk解析SSE',
'  5. 非流式: 等待完整响应json()解析',
'  6. 重试: maxRetries次，间隔递增',
'  7. 429: 等待60秒后重试',
'  8. 空闲检测: chunk间隔超阈值触发idle回调',
'',
'### 2. _callAiApi(prompt, systemPrompt, skillIds)',
'- 位置: renderer_v2.js L4918',
'- 职责: 业务功能封装(设定/伏笔/命名/规则/时间线)',
'- 行为: 构建messages -> 注入Skill -> 直接fetch(非流式) -> 返回结果',
'- 调用者: decomposeOutline, extractForeshadowing, generateNames, generateWritingRules, extractTimeline, showChapterOverview, batchReviewChapters, reviseChapter',
'',
'### 3. streamChat(userText, aiMsg) - 聊天流式',
'- 位置: renderer_v2.js L2599',
'- 行为: 构建messages -> 注入Skill+Agent -> _aiRequest流式 -> 逐chunk更新DOM -> 保存chatHistory',
'',
'### 4. apiGenerate(type, params, onChunk, opts) - 流水线生成',
'- 位置: renderer_v2.js L2185',
'- 行为: type构建prompt -> 有skills走SkillExecutionEngine.chain() -> 无skills走_aiRequest -> onChunk回调',
'',
'## 重试与错误处理',
'- maxRetries: 通常3次',
'- retryDelays: 递增间隔数组',
'- 429: 等待60秒后重试(不消耗正常重试)',
'- 最终失败: throw lastErr || new Error(_aiRequest failed)',
'',
'## 空闲检测(防断网)',
'- 位置: L2399',
'- 流式模式下chunk间隔超阈值 -> resolve(idle) -> Promise.race -> reader.cancel',
'',
'## 调用链分类',
'- A.聊天: streamChat -> _aiRequest(stream) -> SSE -> onChunk -> chatHistory',
'- B.流水线: apiGenerate -> SkillExecutionEngine.chain/_aiRequest -> onChunk',
'- C.业务: _callAiApi -> fetch(非流式) -> json() -> 返回',
'- D.去AI味: deAiProcess -> chain/splitMerge/multiStep分支',
'- E.模型获取: fetchModelList -> IPC -> 主进程fetch /models',
'- F.测试连接: testConnection -> 10s超时 -> IPC fetchModels',
'- G.GitHub: searchGitHub -> 30s超时 -> fetch GitHub API',
'',
'## 迁移注意',
'1. _aiRequest是唯一入口，Vue3封装为apiService',
'2. 429等待60秒硬编码需提取配置项',
'3. _callAiApi直接fetch不走_aiRequest，历史遗留需统一',
'4. fetchModelList走IPC绕CORS需保留',
'5. streamChat的onChunk直接操作DOM，Vue3改响应式',
''].join('\n');
files['T03_功能系统层.md'] = [
'# T03 - 功能系统层',
'',
'## 功能系统清单',
'',
'### 1. 生成流水线 (pipeline-manager.js 125KB)',
'- 入口: btn-pipeline -> showPipeline()',
'- 5步: 大纲 -> 设定 -> 卷纲 -> 章节 -> 正文',
'- 每步Skill绑定: pl-s1-skill ~ pl-s5-skill',
'- 卷纲4模式: AI生成/自动生成/逐卷生成/批量续生成',
'- 章节参数: 每章字数 + 每批次生成数(默认5)',
'- 断网续接: 已生成章节保留，断点继续',
'',
'### 2. 去AI味 (de-ai.js 114KB, renderer_v2.js L587-800)',
'- 入口: btn-de-ai -> deAiProcess()',
'- 3模式: chain(串行)/splitMerge(切分并行)/multiStep(3步控制)',
'- 执行顺序: 硬规则pre -> S1改写 -> 硬规则post -> S2验证',
'- 验证器: first_subject_different, cross_model_check, zhuque_check',
'- 风格样本: DeAiSamples注入最后skill的user message',
'- 温度: rewrite=0.7, verify=0.3',
'- 进度: deai-progress-modal(进度条+步骤+取消)',
'',
'### 3. 聊天对话',
'- 入口: btn-send/Enter -> sendMessage() -> streamChat()',
'- 消息按钮: 复制/重新生成/应用到编辑区',
'- 上下文: Agent systemPrompt + Skill template + 深度控制',
'',
'### 4. 编辑器',
'- 核心: textarea#editor-content',
'- 撤销/重做: document.execCommand(废弃需替代)',
'- 保存: Ctrl+S / 30s自动保存',
'- AI生成/导出(md/txt/epub)/AI起名/写作规则/时间线/批量审阅/章节修订/去AI味',
'- 查找替换: find-replace-bar',
'- 内联AI菜单: 改写/扩写/润色/续写/精简',
'- Diff对比: 原文vs修改，逐处接受/拒绝',
'',
'### 5. 章节树',
'- 树形结构，展开/折叠',
'- 右键菜单: 绑定Skill/生成章节/生成正文',
'- 双击重命名',
'- 卷/章操作: add/toggle/view/del/gen',
'',
'### 6. 设置(6个tab)',
'- API设置: 供应商列表+编辑(名称/URL/Key/模型/流式/温度/MaxTokens/用途/系统提示词)',
'- 技能: 列表+编辑(名称/描述/类别/注入模式/绑定层级/上下文深度/绑定类型/联动/变量/模板)',
'- 智能体: 列表+编辑(名称/模型/温度/MaxTokens/系统提示词)',
'- 外观: 主题/字体/自动保存间隔',
'- 去AI味: 3模式卡片+SKILL选择器+Agent选择器+硬规则开关+流程预览',
'- 诊断日志: 查看/导出/清除',
'',
'### 7-12. 其他系统',
'- 大纲工作台: 编辑+AI共创',
'- 设定合集: 分类管理',
'- 记忆面板: 分类+条目CRUD',
'- 插件市场: GitHub Token+搜索+分页+安装',
'- 仪表盘: 写作统计',
'- 主题: 暗色/亮色切换',
'',
'## 迁移注意',
'1. pipeline(125KB)+de-ai(114KB)需拆分多组件+composable',
'2. 去AI味3模式分支改策略模式',
'3. execCommand废弃需CodeMirror或自实现undo栈',
'4. 章节树右键+拖拽需Vue3组件库',
'5. 6个tab改Vue Router式tab组件',
''].join('\n');
files['T04_交互流程层.md'] = [
'# T04 - 交互流程层',
'',
'## 启动流程',
'Electron -> main.js创建窗口 -> renderer.html -> script按序加载 -> App.init() -> 加载storage -> 恢复lastSession -> 渲染章节树 -> 打开上次章节',
'',
'## 核心工作流',
'',
'### 工作流1: 新建项目',
'项目按钮 -> openProjectModal -> 新建 -> createProject -> 章节树渲染 -> 选章 -> openChapter -> 编辑器加载',
'',
'### 工作流2: 生成流水线',
'流水线按钮 -> showPipeline -> Step1大纲(编辑+字数+Skill+确认) -> Step2设定(AI生成+编辑+保存+确认) -> Step3卷纲(4模式+卡片编辑+确认) -> Step4章节(字数+批次+选卷+生成+卡片编辑) -> Step5正文(选章+字数+AI生成+插入)',
'',
'### 工作流3: AI对话',
'选Agent+Model -> 输入消息 -> 发送/Enter -> 流式回复 -> 消息操作(复制/重新生成/应用) -> Skill区显示',
'',
'### 工作流4: 去AI味',
'编辑器选文本 -> 点去AI味 -> 进度模态框 -> 内部(chain/splitMerge/multiStep + 验证器 + 硬规则) -> 写回编辑器/diff对比 -> 可取消',
'',
'### 工作流5: 设置供应商',
'设置 -> API tab -> 供应商列表 -> 编辑(名称/URL/Key/获取模型/用途/配置) -> 测试连接(10s超时) -> 保存(加密Key) -> 返回',
'',
'### 工作流6: 章节树操作',
'点击章节->openChapter / 右键->绑定Skill/生成章节/生成正文 / 双击->重命名 / 卷展开折叠 / 添加删除',
'',
'### 工作流7: 内联AI编辑',
'选中文本 -> inline-menu(改写/扩写/润色/续写/精简) -> API -> diff-modal(原文vs修改) -> 逐处/全部接受拒绝 -> 应用',
'',
'### 工作流8: 插件市场',
'插件市场 -> GitHub Token -> 搜索(关键词+分类+排序) -> 分页浏览 -> 安装(下载README)',
'',
'## 面板管理',
'- 13个模态框/面板，各有show/close方法',
'- backdrop点击关闭',
'- ESC关闭全部(L64)',
'- 切换时自动关闭其他',
'',
'## 迁移注意',
'1. 面板改路由/条件渲染组件',
'2. backdrop用@click.self',
'3. ESC全局keydown处理',
'4. 流水线5步改stepper组件',
'5. 右键菜单需ContextMenu组件',
'6. 内联菜单需编辑器组件选中文本检测',
''].join('\n');
files['T05_渲染层.md'] = [
'# T05 - 渲染层',
'',
'## DOM顶层结构',
'- header#app-header: app-title + agent-select + model-select + btn-clear',
'- main: panel-backdrop + breadcrumb-bar + app-body',
'- app-body: app-sidebar + app-main(chapter-tree + editor-panel + chat-panel)',
'- 13个模态框/浮层: settings/memory/ctx-menu/skill-bind/plugin-market/toast/tooltip/diff/inline-menu/loading/deai-progress/exit-confirm',
'',
'## 侧栏8按钮',
'大纲工作台/设定合集/生成流水线/记忆/插件市场/设置/仪表盘/主题切换',
'',
'## 编辑器面板',
'editor-header(mode-badge+title+toolbar) + find-replace-bar + textarea#editor-content',
'toolbar: 撤销/重做/生成/保存/导出/AI起名/写作规则/时间线/批量审阅/章节修订/去AI味 + word-count',
'',
'## 聊天面板',
'chat-header(标题+agent+model) + context-bar + messages-list + input-row(user-input+btn-send) + skill-area(可折叠) + input-hint',
'',
'## 设置模态框',
'6个tab: API设置/技能/智能体/外观/去AI味/诊断日志',
'',
'## CSS架构',
'1. style.css (7489行) - 主样式',
'2. styles/tokens.css - CSS变量(颜色/字体/间距/边框)',
'3. styles/components/ - app-layout/buttons/modal-panel/form-editor',
'4. notyf.min.css - 通知库',
'',
'## CSS变量系统',
'- 颜色: --bg-primary/secondary, --text-primary/muted, --accent',
'- 字体: --font-size-sm/md/lg, --font-family',
'- 间距: --spacing-xs/sm/md/lg/xl',
'- 主题: 切换变量值(暗色/亮色)',
'',
'## 布局',
'- 三栏: chapter-tree | editor-panel | chat-panel',
'- 可拖拽分隔: resizer-chapter, resizer-editor-chat',
'- 侧栏固定宽度，垂直图标',
'- header顶部固定',
'',
'## 主题',
'- 入口: theme-toggle-btn',
'- 存储: key=app-theme',
'- 实现: body/data-theme属性切换，CSS变量响应',
'',
'## 渲染模式',
'1. innerHTML拼接: 章节树/消息列表/设置列表',
'2. classList切换: modal-hidden/visible/pl-hidden',
'3. style直接操作: 进度条宽度/颜色',
'4. Markdown: marked库转HTML后innerHTML(未做XSS防护)',
'',
'## 迁移注意',
'1. innerHTML改v-for/v-if',
'2. CSS变量可直接迁移',
'3. 三栏+拖拽需vue-resizable',
'4. 主题改provide/inject或Pinia',
'5. Markdown需加DOMPurify',
'6. style.css拆分组件级CSS',
'7. 模态框改Teleport',
'8. resizer需自定义指令',
''].join('\n');
files['T06_事件层.md'] = [
'# T06 - 事件层',
'',
'## 事件绑定模式',
'- addEventListener直接绑定(App.init集中注册)',
'- 事件委托: tree-body用e.target.closest([data-a])分发',
'',
'## 事件清单',
'',
'### 全局',
'- document keydown: ESC关闭所有模态框(L64)',
'- window error: 全局错误捕获',
'- window unhandledrejection: Promise未捕获错误',
'',
'### Header',
'- btn-clear click: clearChat()',
'- agent-select/model-select change: 切换',
'',
'### 侧栏(8按钮)',
'- btn-outline-workspace: openOutlineWorkspace()',
'- btn-settings-collection: showSettingsCollection()',
'- btn-pipeline: showPipeline()',
'- btn-memory: showMemory()',
'- btn-plugin-market: showPluginMarket()',
'- btn-settings: toggleSettings(true)',
'- btn-dashboard: showWritingDashboard()',
'- theme-toggle-btn: 主题切换',
'',
'### 章节树',
'- tree-body click: 事件委托(data-a: view-outline/toggle-vol/view-ch-plot/open-ch/del-ch/add-ch/gen-ch/gen-body/add-vol)',
'- tree-body contextmenu: showContextMenu(e)',
'- tree-body dblclick: 重命名(span->input->blur保存)',
'- btn-open-project: openProjectModal()',
'- btn-tree-gen: showPipeline()',
'- project-list click: 事件委托(pm-open/pm-delete)',
'- btn-new-project/btn-create-project',
'',
'### 编辑器',
'- btn-undo/btn-redo: 撤销/重做',
'- btn-generate-content: generateContent()',
'- btn-save-editor: autoSave() (Ctrl+S)',
'- btn-export: 导出下拉(md/txt/epub)',
'- btn-ai-names: generateNames()',
'- btn-writing-rules: generateWritingRules()',
'- btn-timeline: extractTimeline()',
'- btn-batch-review: batchReviewChapters()',
'- btn-revise: reviseChapter()',
'- btn-de-ai: deAiProcess()',
'- editor-content input: 字数统计',
'- find-replace: find-input/btn-find-prev/next/btn-replace-one/all/btn-find-close',
'',
'### 聊天',
'- btn-send click: sendMessage()',
'- user-input keydown: Enter发送',
'- user-input input: 自动调整高度+字数+发送按钮启用',
'- messages-list click: 事件委托(复制/重新生成/应用)',
'- skill-area-toggle click: 折叠/展开',
'',
'### 设置',
'- btn-close-settings/backdrop: toggleSettings(false)',
'- modal-tab click: 切换tab',
'- btn-toggle-key: 显示/隐藏API Key',
'- btn-provider-back: exitProviderEdit()',
'- btn-fetch-models: fetchModelList()',
'- btn-test-connection: testConnection()',
'- btn-save-settings: saveSettingsFromForm()',
'- btn-export-data/btn-import-data',
'- cfg-temperature input: 温度显示+_formDirty',
'- 各表单元素 input/change: _formDirty=true',
'- btn-add-skill/btn-add-agent',
'- skill-list/agent-list click: 事件委托(编辑/删除)',
'',
'### Diff模态框',
'- btn-close-diff/btn-diff-cancel/backdrop: _closeDiff()',
'- btn-diff-apply: _applyDiffResult()',
'- btn-diff-accept-all/reject-all',
'- btn-diff-prev/next: 逐处导航',
'',
'### 退出确认',
'- btn-exit-cancel/btn-exit-direct/btn-exit-save',
'',
'### 去AI进度',
'- btn-deai-cancel: AbortController.abort()',
'',
'### 插件市场',
'- btn-close-market/backdrop: closePluginMarket()',
'- btn-market-search/market-search-input Enter: searchGitHub()',
'- btn-set-token/btn-token-help/btn-save-token',
'- btn-prev-page/btn-next-page',
'- market-sort/market-category change',
'',
'## 快捷键(hotkeys-js)',
'- Ctrl+Z: 撤销',
'- Ctrl+Y: 重做',
'- Ctrl+S: 保存',
'- ESC: 关闭所有模态框',
'',
'## 迁移注意',
'1. @click/@keydown替代addEventListener',
'2. v-model替代input事件',
'3. 事件委托改v-for+@click',
'4. 快捷键用useMagicKeys或自定义指令',
'5. 全局错误改app.config.errorHandler',
'6. _formDirty改watch或computed',
''].join('\n');
var count = 0;
for (var name in files) {
  fs.writeFileSync(dir + name, files[name], 'utf8');
  console.log('[OK] ' + name + ': ' + files[name].length + ' bytes');
  count++;
}
console.log('Total: ' + count + ' files written');
