const fs = require('fs');
const dir = 'D:/codex/novel-workshop-vue3/_audit/manual/';
const files = {};
files['T07_生命周期层.md'] = [
'# T07 - 生命周期层',
'',
'## 应用生命周期',
'',
'### 启动阶段',
'1. Electron main.js启动 -> 创建BrowserWindow -> 加载renderer.html',
'2. main.js: 单实例锁检测 -> 窗口状态恢复 -> IPC注册',
'3. renderer.html: CSP配置 -> CSS加载(7个文件) -> JS加载(15+个文件按序)',
'4. renderer_v2.js: new App() -> constructor加载storage -> init()',
'5. init(): 加载providers/agents/skills/projects -> 恢复lastSession -> 渲染章节树 -> 打开上次章节',
'6. beforeunload: 最终autoSave + syncTreeToPipeline + 持久化pipeline数据 + 保存lastSession',
'',
'### 运行阶段',
'- 自动保存: setInterval 30秒触发autoSave()',
'- 章节切换: openChapter() -> 加载内容到编辑器 -> 更新word-count',
'- 对话流: sendMessage() -> streamChat() -> 完成后保存chatHistory',
'- 设置变更: 表单input/change触发_formDirty -> 保存时写入storage',
'',
'### 关闭阶段',
'1. Electron onCloseRequest -> 发送IPC到renderer',
'2. renderer显示exit-confirm-modal -> 用户选择(取消/直接退出/保存并退出)',
'3. beforeunload: autoSave + syncTree + persist pipeline + save lastSession',
'4. main.js: window-all-closed -> app.quit()',
'',
'### 数据迁移生命周期',
'- 启动时: 检测旧格式数据 -> 自动迁移(L81-101 try/catch)',
'- 迁移内容: providers格式升级/agents格式升级/skills格式升级',
'- 迁移失败: console.warn但不阻断启动',
'',
'## 组件生命周期',
'',
'### Provider生命周期',
'- 创建: 用户填写表单 -> saveSettingsFromForm() -> 加密apiKey -> StorageManager.set',
'- 修改: 进入编辑视图 -> 修改表单 -> _formDirty=true -> 保存',
'- 删除: 用户确认 -> ProviderManager删除 -> StorageManager持久化 -> 刷新列表',
'- 激活: 下拉选择 -> settings.baseUrl/apiKey/model更新',
'',
'### Skill生命周期',
'- 创建: btn-add-skill -> 表单填写 -> SkillManager.add -> StorageManager持久化',
'- 编辑: 列表点击 -> 表单填充 -> 修改 -> 保存',
'- 删除: 确认 -> SkillManager删除 -> 持久化 -> 刷新',
'- 激活: 绑定到层级(project/volume/chapter) -> getActiveSkills()返回',
'- 测试: testSkill() -> 独立API调用验证',
'',
'### Agent生命周期',
'- 创建/编辑/删除: 同Skill模式',
'- 使用: sendMessage时读取agent.systemPrompt + agent.model + agent.temperature',
'',
'### Project生命周期',
'- 创建: createProject() -> 默认卷+章 -> StorageManager持久化',
'- 打开: openProject(id) -> 加载project数据 -> 渲染章节树',
'- 删除: 确认 -> 级联删除chapters_{projectId} + project-{id} -> 持久化',
'- 孤儿恢复: ProjectManager启动时检测并恢复孤儿数据',
'',
'### Chapter生命周期',
'- 创建: addChapter(vid) -> ChapterManager.add -> 渲染到树',
'- 编辑: openChapter -> editor加载 -> autoSave每30秒',
'- 删除: deleteChapterFromTree -> 确认 -> 级联删除',
'- 重命名: 双击 -> input -> blur保存',
'',
'## 迁移注意',
'1. Vue3用onMounted/onUnmounted替代init/beforeunload',
'2. setInterval改为onMounted中启动+onUnmounted清除',
'3. 数据迁移逻辑应放在store初始化阶段',
'4. beforeunload逻辑需拆分到各store的持久化action',
''].join('\n');
files['T08_持久化层.md'] = [
'# T08 - 持久化层',
'',
'## StorageManager架构',
'- 源文件: js/storage.js',
'- 所有key加wa_前缀',
'- Electron: 走IPC(window.electronAPI.storageRead/Write)',
'- 浏览器: 走localStorage',
'',
'## 持久化键清单',
'1. providers - 供应商列表(含加密的apiKey)',
'2. agents - 智能体列表',
'3. skills - 技能列表',
'4. projects - 项目列表(元数据)',
'5. chapters_{projectId} - 每个项目的卷章结构',
'6. project-{id} - 单个项目的详细数据',
'7. app-settings - 应用设置(baseUrl/apiKey/model等)',
'8. app-deai-config - 去AI味配置',
'9. app-theme - 主题(暗色/亮色)',
'10. lastSession - 上次会话(pid/vid/cid/ts)',
'11. active-profile - 激活配置',
'12. githubToken - GitHub Token',
'',
'## 加密机制',
'- API Key加密: window.electronAPI.encrypt/decrypt',
'- IPC通道: safe:encrypt / safe:decrypt',
'- 存储: 加密后存入providers数组',
'- 读取: 解密后赋值给settings',
'',
'## 持久化时机',
'- 启动时: 读取所有键 -> 初始化各Manager',
'- 表单保存: saveSettingsFromForm -> StorageManager.set',
'- 自动保存: 30秒setInterval -> autoSave',
'- 章节切换: openChapter -> 保存当前章节 -> 加载新章节',
'- 关闭前: beforeunload -> 最终保存',
'- 流水线操作: 每步确认时持久化',
'',
'## 数据导出/导入',
'- 导出: btn-export-data -> 序列化providers+agents+skills -> 下载文件',
'- 导入: btn-import-data -> 选择文件 -> 解析 -> 覆盖storage -> 刷新UI',
'',
'## 迁移注意',
'1. Vue3用Pinia持久化插件替代手动StorageManager',
'2. 加密机制保留IPC方式',
'3. 自动保存改为watch+debounce',
'4. 导出导入改为File API',
''].join('\n');
files['T09_网络层.md'] = [
'# T09 - 网络层',
'',
'## 网络请求分类',
'',
'### 1. AI API请求(OpenAI兼容)',
'- 端点: baseUrl + /chat/completions',
'- 方法: POST',
'- Headers: Authorization Bearer + apiKey, Content-Type application/json',
'- Body: { model, messages, temperature, max_tokens, stream }',
'- 流式: SSE格式(data: {json})',
'- 非流式: 等待完整json响应',
'- 重试: 3次，递增间隔',
'- 429: 等待60秒',
'',
'### 2. 模型列表请求',
'- 端点: baseUrl + /models',
'- 方法: GET',
'- 走IPC: window.electronAPI.fetchModels(baseUrl, apiKey)',
'- 主进程代理: 绕过CORS',
'- 超时: 10秒(testConnection) / 30秒(fetchModelList)',
'',
'### 3. GitHub API请求',
'- 端点: https://api.github.com/search/repositories',
'- Headers: Authorization Bearer + githubToken',
'- 超时: 30秒',
'- 分页: page参数',
'- README下载: https://api.github.com/repos/{fullName}/readme',
'',
'### 4. 流式读取(防断网)',
'- ReadableStream + reader.read()',
'- 空闲检测: setTimeout + Promise.race',
'- 超阈值: reader.cancel() + 触发暂停',
'- AbortController: 用户取消/超时',
'',
'## CSP策略',
'- default-src self',
'- style-src self unsafe-inline',
'- script-src self unsafe-inline',
'- img-src self data: https:',
'- connect-src self https:',
'',
'## 迁移注意',
'1. Vue3+Electron保留IPC代理模式绕CORS',
'2. 流式读取改为fetch + ReadableStream(标准)',
'3. 重试逻辑提取为独立composable',
'4. CSP策略需更新允许Vue3 devserver',
''].join('\n');
files['T10_错误处理层.md'] = [
'# T10 - 错误处理层',
'',
'## 错误处理模式',
'',
'### 1. try/catch包裹',
'- 几乎所有异步操作都有try/catch',
'- catch块: console.warn + DiagLogger.warn + 继续执行(不中断)',
'- 模式: catch(e){console.warn("[WARN] catch #N renderer_v2.js",e);if(window.DiagLogger)DiagLogger.warn("catch","renderer_v2.js #N",e);}',
'- 编号: 每个catch有唯一编号(#1~#24+)方便定位',
'',
'### 2. 全局错误捕获',
'- window.addEventListener(error): console.error [ERR] Uncaught',
'- window.addEventListener(unhandledrejection): console.error [ERR] Unhandled promise',
'',
'### 3. 用户级错误提示',
'- _toast(msg, type): 显示通知(error/warn/success)',
'- _confirm(msg): 确认对话框(删除/清空等危险操作)',
'- 模态框内错误: provider-conn-status显示连接状态',
'',
'### 4. API错误处理',
'- HTTP状态码: 429特殊处理(60秒等待)',
'- 5xx: 重试',
'- 网络错误: 重试3次后throw',
'- JSON解析错误: 尝试resp.clone().json()获取错误body',
'',
'### 5. DiagLogger',
'- 源文件: js/diag.js',
'- 方法: diag(msg)/warn(tag,msg)/error(tag,msg)',
'- 存储: 通过IPC写入诊断日志文件',
'- 查看: 设置 > 诊断日志tab',
'- 操作: 查看/导出/清除',
'',
'## 迁移注意',
'1. Vue3用app.config.errorHandler替代window.error',
'2. try/catch模式保留，但改为async/await风格',
'3. _toast改为通知组件(如vue-toastification)',
'4. DiagLogger改为Pinia store + 日志服务',
''].join('\n');
files['T11_性能层.md'] = [
'# T11 - 性能层',
'',
'## 性能相关机制',
'',
'### 1. 流式输出',
'- AI回复逐字显示，不等待完整响应',
'- requestAnimationFrame用于滚动到底部(L2831)',
'- onChunk直接更新DOM innerHTML',
'',
'### 2. 自动保存节流',
'- setInterval 30秒触发(L3949)',
'- 非每次输入都保存，降低IO压力',
'',
'### 3. 消息输入自适应',
'- user-input input事件: autoResizeInput()调整高度',
'- 防止textarea无限增高',
'',
'### 4. 并行请求(去AI味)',
'- splitMerge模式: Promise.all并行处理切分段落',
'- multiStep模式: parallelMap(items, fn, concurrency)并发控制',
'- concurrency参数限制并发数',
'',
'### 5. 空闲检测(防断网)',
'- 流式chunk间隔超阈值 -> 触发暂停/重连',
'- Promise.race(chunk读取 vs idle timer)',
'',
'### 6. Toast定时清除',
'- 3秒后opacity=0(L4322)',
'- setTimeout控制',
'',
'### 7. AbortController超时',
'- testConnection: 10秒超时',
'- searchGitHub: 30秒超时',
'- fetchModels: AbortSignal.timeout(30000)',
'',
'## 性能瓶颈',
'1. renderer_v2.js(292KB)单文件加载 -> 阻塞渲染',
'2. pipeline-manager.js(125KB) + de-ai.js(114KB)大模块',
'3. innerHTML字符串拼接大量数据时可能卡顿',
'4. 章节树数百章节时无虚拟滚动',
'5. style.css(7489行)单文件',
'',
'## 迁移注意',
'1. Vue3代码分割+懒加载解决大文件问题',
'2. 虚拟滚动组件解决章节树性能',
'3. 响应式数据替代innerHTML拼接',
'4. Pinia持久化插件+debounce替代setInterval',
'5. Tree shaking减少bundle体积',
''].join('\n');
files['T12_配置层.md'] = [
'# T12 - 配置层',
'',
'## 配置分类',
'',
'### 1. 应用设置(app-settings)',
'- baseUrl, apiKey, model',
'- systemPrompt',
'- temperature, maxTokens',
'- streamMode',
'- 存储: StorageManager key=app-settings',
'',
'### 2. 供应商配置(providers)',
'- name, baseUrl, apiKey(加密), model',
'- streamMode, temperature, maxTokens',
'- purpose: generate/verify',
'- systemPrompt',
'- 存储: StorageManager key=providers',
'',
'### 3. 去AI味配置(app-deai-config)',
'- mode: chain/splitMerge/multiStep',
'- skills: [skillId1, skillId2, ...]',
'- agentId',
'- level: light/medium/strong',
'- hardruleEnabled: boolean',
'- splitSize: number(切分字数)',
'- 存储: StorageManager key=app-deai-config',
'',
'### 4. 外观配置',
'- theme: dark/light',
'- fontSize',
'- autoSaveInterval',
'- 存储: StorageManager key=app-theme + app-settings',
'',
'### 5. 流水线配置',
'- 每步Skill绑定(pl-s1~s5)',
'- 全书字数',
'- 期望卷数',
'- 每章字数',
'- 每批次生成数',
'- 存储: pipeline持久化到project数据',
'',
'### 6. 技能配置(skills)',
'- name, desc, category',
'- template(提示词)',
'- injectMode: system_prefix/user_prefix/user_suffix',
'- frequency: every/every3/every5',
'- depth: 上下文深度(0=不限)',
'- bindType: project/volume/chapter',
'- bindTarget/bindTargets',
'- linkedSkills: [id]',
'- 存储: StorageManager key=skills',
'',
'### 7. 智能体配置(agents)',
'- name, model, temperature, maxTokens, systemPrompt',
'- 存储: StorageManager key=agents',
'',
'## 配置读取流程',
'- 启动: StorageManager.get -> 各Manager.init -> App.settings',
'- 运行: 表单保存 -> StorageManager.set -> 刷新UI',
'- 流水线: _plData()读取 -> _plPersist()写入',
'',
'## 迁移注意',
'1. Vue3用Pinia store管理所有配置',
'2. 持久化用pinia-plugin-persistedstate',
'3. 配置schema用TypeScript接口定义',
'4. 去AI味配置改为独立store',
''].join('\n');
files['T13_IPC边界层.md'] = [
'# T13 - IPC边界层',
'',
'## preload.js暴露的IPC API',
'',
'### 存储',
'- storageRead(key) -> IPC -> 主进程读文件',
'- storageWrite(key, value) -> IPC -> 主进程写文件',
'- storageRemove(key) -> IPC -> 主进程删key',
'- storageList() -> IPC -> 主进程列出所有key',
'- storageExport() -> IPC -> 导出全部数据',
'- storageImport(data) -> IPC -> 导入数据',
'',
'### 加密',
'- encrypt(text) -> IPC safe:encrypt -> 主进程加密',
'- decrypt(text) -> IPC safe:decrypt -> 主进程解密',
'',
'### 文件操作',
'- dialogSaveFile(defaultName, content) -> 保存对话框',
'- openFile() -> 打开文件对话框',
'',
'### 生命周期',
'- onFinalSave(callback) -> 监听最终保存事件',
'- onCloseRequest(callback) -> 监听关闭请求',
'- respondCloseChoice(choice) -> 响应关闭选择',
'',
'### 诊断',
'- diagWrite(msg) -> 写诊断日志',
'- diagRead() -> 读诊断日志',
'- diagExport() -> 导出诊断日志',
'- diagClear() -> 清除诊断日志',
'',
'### 网络',
'- fetchModels(baseUrl, apiKey) -> 主进程代理fetch /models',
'',
'## IPC通道安全',
'- preload.js通过contextBridge暴露受限API',
'- 主进程验证channel白名单',
'- 存储路径: Documents/写作助手数据/',
'- safeKey: 替换非ASCII字符用于文件名',
'',
'## 迁移注意',
'1. Vue3+Electron保留contextBridge模式',
'2. IPC API改为TypeScript接口',
'3. 存储路径可配置',
'4. 考虑用electron-store替代手动文件管理',
''].join('\n');
files['T14_应用级状态机.md'] = [
'# T14 - 应用级状态机',
'',
'## 全局状态变量(renderer_v2.js)',
'',
'### App实例状态',
'- currentProjectId: 当前项目ID',
'- currentVolumeId: 当前卷ID',
'- currentChapterId: 当前章节ID',
'- settings: { baseUrl, apiKey, model, systemPrompt, temperature, maxTokens, streamMode }',
'- chatHistory: 聊天历史数组',
'- _deAiConfig: 去AI味配置',
'- _formDirty: 表单是否已修改',
'- _autoSaveTimer: 自动保存timer',
'- _scrollRAF: 滚动动画frame',
'- _toastTimer: 通知定时器',
'',
'### 流水线状态',
'- _plData(): 获取流水线数据(大纲/设定/卷纲/章节/正文)',
'- _plPersist(data): 持久化流水线数据',
'- pipeline当前步骤(1-5)',
'- 每步的Skill绑定',
'- 已生成的卷/章数据',
'',
'### 状态转换',
'1. 无项目 -> 有项目: createProject/openProject',
'2. 有项目 -> 选章: openChapter',
'3. 选章 -> 编辑: editor加载内容',
'4. 编辑 -> AI对话: sendMessage',
'5. 编辑 -> 去AI味: deAiProcess',
'6. 任意 -> 设置: toggleSettings',
'7. 任意 -> 流水线: showPipeline',
'',
'### Manager单例状态',
'- ProviderManager: providers数组 + getVerifyProvider()',
'- AgentManager: agents数组',
'- SkillManager: skills数组 + 绑定关系',
'- ProjectManager: projects数组 + 孤儿恢复',
'- ChapterManager: chapters_{projectId}结构',
'',
'## 迁移注意',
'1. Vue3用Pinia拆分为多个store',
'2. 全局状态改为响应式',
'3. 状态转换用store actions管理',
'4. Manager单例改为store模块',
''].join('\n');
files['T15_编码与文本处理层.md'] = [
'# T15 - 编码与文本处理层',
'',
'## 编码规则',
'- 所有源文件: UTF-8 无BOM',
'- HTML: <meta charset=UTF-8>',
'- 存储: JSON.stringify -> UTF-8写入',
'- 读取: UTF-8读取 -> JSON.parse',
'',
'## 文本处理',
'',
'### 1. Markdown渲染',
'- 库: marked(marked.umd.js)',
'- 用途: 聊天消息HTML渲染',
'- 安全: 旧架构未做XSS sanitize',
'',
'### 2. 字数统计',
'- editor-content input事件 -> 实时计算字数',
'- 显示: #word-count元素',
'- 聊天: #char-count显示输入字数',
'',
'### 3. 查找替换',
'- find-input/replace-input',
'- 上一个/下一个: 高亮匹配',
'- 替换当前/全部替换',
'',
'### 4. 文本导出',
'- Markdown(.md): 直接导出文本',
'- 纯文本(.txt): 去除格式',
'- EPUB(.epub): 需epub生成库',
'',
'### 5. API Key加密',
'- encrypt/decrypt通过IPC到主进程',
'- 主进程使用Node.js crypto模块',
'- 存储时加密，读取时解密',
'',
'### 6. JSON转义',
'- Skill/卷纲/章节输出要求JSON格式',
'- 换行符需转义为\\n',
'- 双引号需转义为\\"',
'- 验证器: json_escape_valid',
'',
'### 7. safeKey处理',
'- 主进程: 替换非ASCII字符用于文件名',
'- 确保存储路径合法',
'',
'## 编码安全规则(规则13)',
'- 禁止PowerShell Set-Content -Encoding UTF8改中文源文件',
'- 修改含中文源文件必须用Node.js fs或apply_patch',
'- 禁止Out-File/Set-Content/Add-Content写含中文源文件',
'',
'## 迁移注意',
'1. Markdown渲染加DOMPurify',
'2. 字数统计用computed',
'3. 查找替换用编辑器库原生功能',
'4. EPUB导出用epub-gen库',
'5. 编码安全规则在Vue3中通过ESLint强制',
''].join('\n');
files['T16_安全边界层.md'] = [
'# T16 - 安全边界层',
'',
'## CSP策略(renderer.html)',
'```',
'default-src self;',
'style-src self unsafe-inline;',
'script-src self unsafe-inline;',
'img-src self data: https:;',
'connect-src self https:;',
'```',
'',
'## API Key安全',
'- 存储: 加密后存入providers(encrypt via IPC)',
'- 传输: 仅在fetch headers中使用',
'- 显示: 密码框(type=password) + 显示/隐藏切换',
'- 日志: 不输出apiKey明文',
'',
'## IPC安全',
'- contextBridge暴露受限API',
'- channel白名单验证',
'- 存储路径限定: Documents/写作助手数据/',
'',
'## XSS风险',
'- 聊天消息: marked()转HTML后innerHTML(未sanitize)',
'- SKILL template: 可能包含用户输入',
'- 风险: 如果API返回恶意HTML，可能执行XSS',
'',
'## GitHub Token安全',
'- 存储: StorageManager key=githubToken',
'- 使用: 仅在GitHub API请求headers中',
'- 说明: 需public_repo权限',
'',
'## 用户确认机制',
'- 删除操作: _confirm()确认',
'- 清空对话: _confirm()确认',
'- 覆盖编辑器: _confirm()确认',
'- 退出应用: exit-confirm-modal',
'',
'## 迁移注意',
'1. Vue3加DOMPurify做XSS防护',
'2. CSP策略更新(允许Vue3 devserver)',
'3. API Key改用electron-store加密存储',
'4. GitHub Token改用keytar(系统密钥环)',
'5. 用户确认改为Vue3确认对话框组件',
''].join('\n');
files['T17_版本迁移层.md'] = [
'# T17 - 版本迁移层',
'',
'## 数据迁移机制',
'- 位置: renderer_v2.js L81-101',
'- 时机: 应用启动时自动执行',
'- 策略: try/catch包裹，失败不阻断启动',
'',
'## 迁移内容',
'',
'### Provider格式升级',
'- 旧: 单一provider对象 { baseUrl, apiKey, model }',
'- 新: providers数组 [{ id, name, baseUrl, apiKey, model, purpose, ... }]',
'- 迁移: 旧对象包装为新数组',
'',
'### Agent格式升级',
'- 字段可能新增/重命名',
'',
'### Skill格式升级',
'- 旧: 无bindTargets字段',
'- 新: 支持 bindTarget + bindTargets 双绑定',
'- 迁移: bindTarget自动转为bindTargets',
'',
'### 去AI味配置升级',
'- 旧: 无mode字段(只有串行)',
'- 新: mode: chain/splitMerge/multiStep',
'- 迁移: 无mode默认设为chain',
'',
'## 应用版本号',
'- 当前: 2.7.63(安装包文件名)',
'- 版本位置: package.json',
'- 版本显示: 可能不在UI中展示',
'',
'## 迁移注意',
'1. Vue3用结构化迁移框架(如vue-migration)',
'2. 迁移逻辑放在store初始化阶段',
'3. 迁移前自动备份数据',
'4. 迁移失败提供回滚机制',
''].join('\n');
files['T18_焦点与无障碍层.md'] = [
'# T18 - 焦点与无障碍层',
'',
'## tabindex',
'- 所有交互元素都有tabindex=0',
'- 按钮: <button tabindex=0>',
'- 输入: <input/textarea tabindex=0>',
'- 选择: <select tabindex=0>',
'',
'## aria-label',
'- 所有按钮都有aria-label',
'- 示例: btn-clear aria-label=清空对话',
'- 示例: btn-settings aria-label=设置',
'- 选择器: agent-select aria-label=选择智能体',
'',
'## title提示',
'- 按钮有title属性(原生tooltip)',
'- 示例: btn-undo title=Ctrl+Z',
'- 示例: btn-save-editor title=Ctrl+S',
'',
'## data-tooltip',
'- 侧栏按钮有data-tooltip属性',
'- 自定义tooltip组件(#tooltip元素)',
'',
'## 焦点管理',
'- 模态框打开时焦点应trap在模态框内(旧架构可能未实现)',
'- ESC关闭模态框',
'- 模态框关闭后焦点应回到触发元素(旧架构可能未实现)',
'',
'## 迁移注意',
'1. Vue3用v-focus指令或@focus/@blur',
'2. aria-label用Vue3绑定(:aria-label)',
'3. tooltip用Vue3组件(如v-tooltip)',
'4. 焦点trap用vue-focus-trap',
'5. 模态框焦点管理用Teleport + focus-trap',
''].join('\n');
files['T19_构建与打包层.md'] = [
'# T19 - 构建与打包层',
'',
'## 旧架构构建',
'- 无构建步骤: 纯HTML+CSS+JS直接运行',
'- 无打包工具: 不需要webpack/vite',
'- 依赖: node_modules直接引用(hotkeys-js/notyf/marked)',
'',
'## Electron打包',
'- 工具: electron-builder',
'- 配置: package.json中的build字段',
'- 输出: dist/写作助手-Setup-{version}.exe',
'- 当前版本: 2.7.63',
'',
'## 打包前检查(规则)',
'1. CSS花括号平衡检查(深度为0)',
'2. 重复选择器检测(非媒体查询真冲突为0)',
'3. 临时文件清理(_cdp_test.js等)',
'4. 版本号更新',
'5. node --check语法验证',
'',
'## 文件结构',
'- 主进程: main.js',
'- Preload: preload.js',
'- 渲染进程: renderer.html + style.css + js/*.js + renderer_v2.js + panels.js',
'- 依赖: node_modules/(hotkeys-js/notyf/marked)',
'- 样式: styles/tokens.css + styles/components/*.css',
'',
'## 迁移注意(Vue3)',
'1. Vite构建替代无构建模式',
'2. electron-builder配置更新(vite build输出)',
'3. preload改为TypeScript',
'4. node_modules改为打包时bundle(vite)',
'5. CSS拆分到Vue组件scoped style',
'6. 打包前检查自动化(vite plugin)',
''].join('\n');
files['T20_定时器与异步层.md'] = [
'# T20 - 定时器与异步层',
'',
'## 定时器',
'',
'### setInterval',
'- 自动保存: setInterval(autoSave, 30000) L3949',
'- 用途: 每30秒自动保存编辑器内容',
'',
'### setTimeout',
'- Toast清除: 3秒后opacity=0 (L4322)',
'- 重试延迟: retryDelays[attempt] (L2351/2440/2448)',
'- 429等待: 60秒 (L2460)',
'- 流式idle检测: _idleThreshold (L2399)',
'- 重新加载: 2秒后location.reload (L291)',
'- 测试连接超时: 10秒 (L2029)',
'- GitHub搜索超时: 30秒 (L4742)',
'- 滚动到底部: setTimeout在RAF后 (L2835)',
'',
'### requestAnimationFrame',
'- 滚动到底部: _scrollRAF (L2831)',
'- 用途: 平滑滚动到消息底部',
'',
'## 异步模式',
'',
'### async/await',
'- _aiRequest: async函数，await fetch',
'- streamChat: async，await _aiRequest',
'- sendMessage: async，await streamChat',
'- deAiProcess: async，await各步骤',
'- apiGenerate: async，await SkillExecutionEngine.chain',
'- _callAiApi: async，await fetch',
'',
'### Promise.all',
'- splitMerge: Promise.all并行处理切分段落',
'- parallelMap: Promise.all(workers) (L1055)',
'',
'### Promise.race',
'- 空闲检测: Promise.race([chunkPromise, idlePromise]) (L2401)',
'',
'### AbortController',
'- 去AI味取消: cancelController.signal (L599/623)',
'- 测试连接: controller.abort() 10秒 (L2029)',
'- GitHub搜索: controller.abort() 30秒 (L4742)',
'- fetchModels: AbortSignal.timeout(30000) (L4844)',
'',
'## 迁移注意',
'1. setInterval改为onMounted启动+onUnmounted清除',
'2. setTimeout改为Vue3的useTimeoutFn',
'3. AbortController保留，封装到composable',
'4. parallelMap可替换为p-limit等库',
''].join('\n');
files['T21_Electron主进程层.md'] = [
'# T21 - Electron主进程层',
'',
'## main.js架构',
'- 源文件: main.js (15KB)',
'- 职责: 窗口管理 + IPC处理 + 存储代理 + 加密 + 诊断日志',
'',
'## 窗口管理',
'- 创建BrowserWindow',
'- 单实例锁: second-instance事件处理',
'- 窗口状态持久化: 位置/大小保存恢复',
'- 加载文件: renderer.html (开发) 或打包后路径',
'',
'## 存储路径',
'- 数据目录: Documents/写作助手数据/',
'- safeKey: 替换非ASCII字符用于文件名',
'- 文件格式: 每个key一个文件({key}.json)',
'',
'## IPC处理',
'',
'### 存储IPC',
'- storage:read -> 读取key文件',
'- storage:write -> 写入key文件',
'- storage:remove -> 删除key文件',
'- storage:list -> 列出所有key',
'- storage:export -> 导出全部数据',
'- storage:import -> 导入数据',
'',
'### 加密IPC',
'- safe:encrypt -> crypto加密',
'- safe:decrypt -> crypto解密',
'',
'### 文件IPC',
'- dialog:saveFile -> 保存对话框',
'- dialog:openFile -> 打开文件对话框',
'',
'### 诊断IPC',
'- diag:write -> 写诊断日志',
'- diag:read -> 读诊断日志',
'- diag:export -> 导出诊断日志',
'- diag:clear -> 清除诊断日志',
'',
'### 网络IPC',
'- fetch:models -> 主进程fetch /models(绕CORS)',
'',
'### 生命周期IPC',
'- close:request -> 关闭请求',
'- close:choice -> 关闭选择响应',
'- final:save -> 最终保存',
'',
'## 错误处理',
'- 主进程错误日志',
'- IPC异常捕获',
'',
'## 迁移注意',
'1. main.js改为TypeScript',
'2. IPC改为结构化(electron-trpc或自定义类型)',
'3. 存储改用electron-store',
'4. 加密改用electron safeStorage API',
'5. 窗口状态用electron-window-state库',
''].join('\n');
files['T22_数据流向层.md'] = [
'# T22 - 数据流向层',
'',
'## 核心数据流',
'',
'### 1. 聊天数据流',
'```',
'用户输入 -> sendMessage() -> 构建messages(历史+Skill+Agent) -> _aiRequest(stream) -> SSE chunks -> onChunk更新DOM -> chatHistory.push -> 渲染messages-list',
'```',
'',
'### 2. 流水线数据流',
'```',
'Step1大纲: textarea -> 确认 -> 保存到project',
'Step2设定: AI生成 -> pl-settings-result -> 保存到设定合集',
'Step3卷纲: AI生成 -> pl-volume-cards -> 确认 -> 写入chapters结构',
'Step4章节: AI生成 -> pl-chapter-cards -> 确认 -> 写入chapters结构',
'Step5正文: AI生成 -> pl-body-result -> 插入编辑器/保存到chapter',
'```',
'',
'### 3. 去AI味数据流',
'```',
'editor文本 -> deAiProcess() ->',
'  硬规则pre(全量20条) ->',
'  分支:',
'    chain: S1(改写) -> S2(验证) -> ...',
'    splitMerge: 切分 -> Promise.all并行重述 -> 拼接',
'    multiStep: Step1(事件核) -> Step2(视角偏转) -> Step3(重组) -> S2',
'  -> 硬规则post(安全子集) ->',
'  -> 验证器(first_subject_different + cross_model_check) ->',
'  -> 写回editor / diff-modal',
'```',
'',
'### 4. 设置数据流',
'```',
'表单input -> _formDirty=true -> 保存按钮 -> saveSettingsFromForm() -> 加密apiKey -> StorageManager.set -> 刷新UI',
'```',
'',
'### 5. 章节数据流',
'```',
'tree-body click -> openChapter(vid,cid) -> ChapterManager.get -> editor加载内容 -> 修改 -> autoSave -> StorageManager.set',
'```',
'',
'### 6. 持久化数据流',
'```',
'App数据 -> StorageManager.set(key, value) -> IPC storageWrite -> 主进程fs.writeFileSync -> {key}.json文件',
'{key}.json文件 -> 主进程fs.readFileSync -> IPC storageRead -> StorageManager.get(key) -> JSON.parse -> App数据',
'```',
'',
'## 跨层数据传递',
'- Skill -> AI调用: SkillManager.getActiveSkills()返回template -> 拼接到messages',
'- Agent -> AI调用: AgentManager.get(id) -> model + temperature + systemPrompt',
'- Provider -> AI调用: ProviderManager -> baseUrl + apiKey(解密)',
'- Pipeline -> Chapter: 确认章节 -> ChapterManager.add -> 章节树渲染',
'- 设定 -> 卷纲: 设定合集数据作为卷纲生成的上下文',
'- 卷纲 -> 章节: 卷纲outline作为章节生成的输入',
'- 章节 -> 正文: 章节plot作为正文生成的输入',
'',
'## 迁移注意',
'1. Vue3用Pinia store管理数据流',
'2. 跨层数据用store actions传递',
'3. 持久化用pinia-plugin-persistedstate',
'4. AI调用数据流封装到apiService composable',
''].join('\n');
files['T23_外部依赖层.md'] = [
'# T23 - 外部依赖层',
'',
'## npm依赖',
'',
'### 运行时依赖',
'1. hotkeys-js: 快捷键库',
'   - 用途: Ctrl+Z/Y/S等快捷键',
'   - 加载: <script src=node_modules/hotkeys-js/dist/hotkeys-js.min.js>',
'2. notyf: 通知库',
'   - 用途: Toast通知',
'   - 加载: <script src=node_modules/notyf/notyf.min.js> + CSS',
'3. marked: Markdown渲染库',
'   - 用途: 聊天消息Markdown转HTML',
'   - 加载: <script src=node_modules/marked/lib/marked.umd.js>',
'',
'### 开发依赖',
'- electron: 桌面应用框架',
'- electron-builder: 打包工具',
'',
'## 外部服务依赖',
'',
'### 1. AI API服务(OpenAI兼容)',
'- 用户自行配置供应商(baseUrl + apiKey)',
'- 端点: /chat/completions(对话) + /models(模型列表)',
'- 兼容: OpenAI/Deepseek/CloudAI等',
'',
'### 2. GitHub API',
'- 用途: 插件市场搜索仓库',
'- 端点: api.github.com/search/repositories',
'- 认证: Personal Access Token(public_repo权限)',
'',
'### 3. 朱雀AI检测(可选)',
'- 用途: 去AI味效果验证(zhuque_check验证器)',
'- 端点: matrix.tencent.com/ai-detect',
'- 限制: 每日次数限制',
'',
'## 文件系统依赖',
'- 数据目录: Documents/写作助手数据/',
'- 诊断日志: 同目录下diag文件',
'- 导出文件: 用户选择路径(对话框)',
'',
'## 迁移注意',
'1. npm依赖改为Vue3生态: hotkeys-js保留, notyf改vue-toastification, marked保留',
'2. AI API服务封装为apiService模块',
'3. GitHub API封装为githubService',
'4. 朱雀检测封装为可选验证器模块',
'5. 文件系统操作走IPC保留',
'6. 考虑添加更多AI供应商适配器',
''].join('\n');
var count = 0;
for (var name in files) {
  fs.writeFileSync(dir + name, files[name], 'utf8');
  console.log('[OK] ' + name + ': ' + files[name].length + ' bytes');
  count++;
}
console.log('Total: ' + count + ' files written');
