import sys
with open("D:/codex/novel-workshop-vue3/_audit/scripts/verify_phaseE_v2.js", "w", encoding="utf-8") as f:
    f.write('const { chromium } = require("playwright");\n')
    f.write('(async () => {\n')
    f.write('  const browser = await chromium.connectOverCDP("http://localhost:9227");\n')
    f.write('  const pages = browser.contexts()[0].pages();\n')
    f.write('  const page = pages[0];\n')
    f.write('  await page.waitForTimeout(2000);\n')
    f.write('  const results = { passed: 0, failed: 0, checks: [] };\n')
    f.write('  function check(name, ok, detail) {\n')
    f.write('    if (ok) results.passed++; else results.failed++;\n')
    f.write('    results.checks.push({ name, ok, detail });\n')
    f.write('    console.log((ok ? "PASS" : "FAIL") + ": " + name + (detail ? " - " + detail : ""));\n')
    f.write('  }\n')
    f.write('  const mcpStoreExists = await page.evaluate(() => {\n')
    f.write('    try {\n')
    f.write('      const pinia = window.__pinia;\n')
    f.write('      if (!pinia) return false;\n')
    f.write('      return !!(pinia._s && pinia._s.has("mcp"));\n')
    f.write('    } catch(e) { return false; }\n')
    f.write('  });\n')
    f.write('  check("MCP store registered", mcpStoreExists, mcpStoreExists ? "found" : "not found");\n')
    f.write('  const settingsBtn = await page.$("#btn-settings");\n')
    f.write('  check("settings button (#btn-settings)", !!settingsBtn, settingsBtn ? "found" : "not found");\n')
    f.write('  if (settingsBtn) {\n')
    f.write('    await page.evaluate((el) => el.click(), settingsBtn);\n')
    f.write('    await page.waitForTimeout(1000);\n')
    f.write('    const mcpTab = await page.$("#tab-mcp");\n')
    f.write('    check("MCP tab in settings", !!mcpTab, mcpTab ? "found" : "not found");\n')
    f.write('    if (mcpTab) {\n')
    f.write('      const text = await mcpTab.textContent();\n')
    f.write('      check("MCP tab label", text === "MCP", text);\n')
    f.write('      await page.evaluate((el) => el.click(), mcpTab);\n')
    f.write('      await page.waitForTimeout(500);\n')
    f.write('      const mcpHeader = await page.$(".mcp-header h4");\n')
    f.write('      check("MCP settings header", !!mcpHeader, mcpHeader ? await mcpHeader.textContent() : "not found");\n')
    f.write('      const addBtn = await page.$(".mcp-header .btn-primary");\n')
    f.write('      check("MCP add server button", !!addBtn, addBtn ? "found" : "not found");\n')
    f.write('      const mcpStoreAfter = await page.evaluate(() => {\n')
    f.write('        try {\n')
    f.write('          const pinia = window.__pinia;\n')
    f.write('          if (!pinia) return false;\n')
    f.write('          return !!(pinia._s && pinia._s.has("mcp"));\n')
    f.write('        } catch(e) { return false; }\n')
    f.write('      });\n')
    f.write('      check("MCP store after tab click", mcpStoreAfter, mcpStoreAfter ? "found" : "not found");\n')
    f.write('    }\n')
    f.write('  }\n')
    f.write('  console.log("");\n')
    f.write('  console.log("========================================");\n')
    f.write('  console.log("Phase E Verification: " + results.passed + "/" + (results.passed + results.failed) + " passed");\n')
    f.write('  console.log("========================================\n");\n')
    f.write('  await browser.close();\n')
    f.write('})();\n')
print("OK")
